#ifndef C_CDD_TESTS_MOCKS_SIMPLE_H
#define C_CDD_TESTS_MOCKS_SIMPLE_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "simple_mocks_export.h"

/** @brief haz */
struct Haz *haz;
};

extern SIMPLE_MOCKS_EXPORT /**
 * @brief Autogenerated docstring
 */
void Foo_cleanup(struct Foo *);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* !C_CDD_TESTS_MOCKS_SIMPLE_H */
