/* clang-format off */
#include <stdlib.h>

#include "simple.h"
/* clang-format on */

/** \brief func */
/**
 * @brief Autogenerated docstring
 */
void Haz_cleanup(struct Haz *haz) { free(haz); }

/** \brief func */
/**
 * @brief Autogenerated docstring
 */
void Foo_cleanup(struct Foo *foo) {
  if (foo == NULL)
    return;
  Haz_cleanup(foo->haz);
  free(foo);
}
