/**
 * @file test_codegen_enum.c
 * @brief Unit tests for Enum code generation module.
 *
 * Verifies correctness of `_to_str` and `_from_str` syntax,
 * ensures robustness against NULL inputs, and verifies guard macro injection.
 *
 * @author Samuel Marks
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <greatest.h>

#include "c_cdd_stdbool.h"
#include "classes/emit_enum.h"

/* Standard definitions for greatest library */
GREATEST_MAIN_DEFS();

/**
 * @brief Setup: Create a basic enum member list for testing.
 */
static void setup_basic_enum(struct EnumMembers *em) {
  enum_members_init(em);
  enum_members_add(em, "RED");
  enum_members_add(em, "GREEN");
}

/**
 * @brief Verify logic generated by write_enum_to_str_func.
 */
TEST test_enum_to_str_basic(void) {
  FILE *tmp = tmpfile();
  struct EnumMembers em;
  long sz;
  char *content;

  ASSERT(tmp != NULL);
  setup_basic_enum(&em);

  ASSERT_EQ(0, write_enum_to_str_func(tmp, "Color", &em, NULL));

  fseek(tmp, 0, SEEK_END);
  sz = ftell(tmp);
  rewind(tmp);

  content = (char *)calloc(1, sz + 1);
  ASSERT(content != NULL);
  fread(content, 1, sz, tmp);

  /* Verify generated code structure */
  ASSERT(strstr(content, "int Color_to_str(enum Color val, char **str_out)"));
  ASSERT(strstr(content, "case Color_RED:"));
  ASSERT(
      strstr(content, "*str_out = strdup(\"RED\");")); /* or _strdup on win */
  /* Ensure UNKNOWN sentinel is handled */
  ASSERT(strstr(content, "case Color_UNKNOWN:"));

  free(content);
  enum_members_free(&em);
  fclose(tmp);
  PASS();
}

/**
 * @brief Verify logic generated by write_enum_from_str_func.
 */
TEST test_enum_from_str_basic(void) {
  FILE *tmp = tmpfile();
  struct EnumMembers em;
  long sz;
  char *content;

  ASSERT(tmp != NULL);
  setup_basic_enum(&em);

  ASSERT_EQ(0, write_enum_from_str_func(tmp, "Color", &em, NULL));

  fseek(tmp, 0, SEEK_END);
  sz = ftell(tmp);
  rewind(tmp);

  content = (char *)calloc(1, sz + 1);
  ASSERT(content != NULL);
  fread(content, 1, sz, tmp);

  /* Verify generated code structure */
  ASSERT(strstr(content,
                "int Color_from_str(const char *const str, enum Color *val)"));
  ASSERT(strstr(content, "strcmp(str, \"GREEN\") == 0"));
  ASSERT(strstr(content, "*val = Color_GREEN;"));
  /* Ensure fallback */
  ASSERT(strstr(content, "*val = Color_UNKNOWN;"));

  free(content);
  enum_members_free(&em);
  fclose(tmp);
  PASS();
}

/**
 * @brief Verify guard macro injection.
 */
TEST test_enum_guards(void) {
  FILE *tmp = tmpfile();
  struct EnumMembers em;
  struct CodegenEnumConfig config;
  long sz;
  char *content;

  ASSERT(tmp != NULL);
  setup_basic_enum(&em);

  memset(&config, 0, sizeof(config));
  config.guard_macro = "USE_ENUMS";

  ASSERT_EQ(0, write_enum_from_str_func(tmp, "Color", &em, &config));

  fseek(tmp, 0, SEEK_END);
  sz = ftell(tmp);
  rewind(tmp);

  content = (char *)calloc(1, sz + 1);
  fread(content, 1, sz, tmp);

  ASSERT(strstr(content, "#ifdef USE_ENUMS"));
  ASSERT(strstr(content, "#endif /* USE_ENUMS */"));

  free(content);
  enum_members_free(&em);
  fclose(tmp);
  PASS();
}

/**
 * @brief Check behaviors with NULL arguments.
 */
TEST test_enum_null_safety(void) {
  struct EnumMembers em;
  FILE *f = tmpfile(); /* Valid file */

  setup_basic_enum(&em);

  ASSERT_EQ(EINVAL, write_enum_to_str_func(NULL, "E", &em, NULL));
  ASSERT_EQ(EINVAL, write_enum_to_str_func(f, NULL, &em, NULL));
  ASSERT_EQ(EINVAL, write_enum_to_str_func(f, "E", NULL, NULL));

  ASSERT_EQ(EINVAL, write_enum_from_str_func(NULL, "E", &em, NULL));
  ASSERT_EQ(EINVAL, write_enum_from_str_func(f, NULL, &em, NULL));
  ASSERT_EQ(EINVAL, write_enum_from_str_func(f, "E", NULL, NULL));

  fclose(f);
  enum_members_free(&em);
  PASS();
}

/**
 * @brief Unit Test Runners
 */
SUITE(codegen_enum_suite) {
  RUN_TEST(test_enum_to_str_basic);
  RUN_TEST(test_enum_from_str_basic);
  RUN_TEST(test_enum_guards);
  RUN_TEST(test_enum_null_safety);
}

int main(int argc, char **argv) {
  GREATEST_MAIN_BEGIN();
  RUN_SUITE(codegen_enum_suite);
  GREATEST_MAIN_END();
}
