/**
 * @file test_integration_server.h
 * @brief Integration tests verifying the Transport Layer against a live Mock
 * Server.
 *
 * Tests:
 * 1. Server Lifecycle (Start/Stop).
 * 2. Libcurl Transport (if available) -> Mock Server.
 * 3. WinHTTP Transport (if available) -> Mock Server.
 *
 * Verifies that the generated client structures (`HttpRequest`) correctly
 * map to on-wire bytes (Headers, Method, URL).
 *
 * @author Samuel Marks
 */

#ifndef TEST_INTEGRATION_SERVER_H
#define TEST_INTEGRATION_SERVER_H

#include <greatest.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cdd_test_helpers/mock_server.h"
#include "functions/parse/http_curl.h"
#include "functions/parse/http_types.h"
#include "functions/parse/http_winhttp.h"
#include "functions/parse/str.h"

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
#define strdup _strdup
#endif

/* --- Mock Server Lifecycle Test --- */

/**
 * @brief Autogenerated docstring
 */
int test_mock_server_lifecycle(TEST *_out_val) {
  MockServerPtr server = NULL;
  mock_server_init(&server);
  ASSERT(server != NULL);

  if (mock_server_start(server) != 0) {
    mock_server_destroy(server);
    SKIPm("Mock server start failed (sockets unavailable?)");
  }
  ASSERT(mock_server_get_port(server) > 0);

  mock_server_destroy(server);
  PASS();
}

/* --- Helper: Generic Transport Test Logic --- */

static /**
 * @brief Autogenerated docstring
 */
void verify_request_content(struct MockServerRequest *req,
                                   const char *expected_method,
                                   const char *expected_path) {
  /* Primitive HTTP parsing for verification */
  /* Request line: METHOD PATH HTTP/1.1 */
  char line[256];

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(line, sizeof(line), "%s %s", expected_method, expected_path);
#else
  sprintf(line, "%s %s", expected_method, expected_path);
#endif

  /* Check if raw header contains the method and path */
  if (strstr(req->raw_header, line) == NULL) {
    fprintf(stderr, "Expected request line '%s' not found in:\n%s\n", line,
            req->raw_header);
    /* Ideally generic fail, but assert here for context */
  }
}

/* --- Curl Integration --- */

/**
 * @brief Autogenerated docstring
 */
int test_curl_transport_integration(TEST *_out_val) {
#ifdef C_CDD_USE_LIBCURL
  char *_ast_strdup_0 = NULL;
  char *_ast_strdup_1 = NULL;
  MockServerPtr server;
  struct HttpClient client;
  struct HttpRequest req;
  struct HttpResponse *res = NULL;
  struct MockServerRequest captured;
  int port;
  char url[128];
  int rc;

  /* SKIPm("Hangs in this environment"); */

  /* 1. Start Server */
  mock_server_init(&server);
  ASSERT(server);
  if (mock_server_start(server) != 0) {
    mock_server_destroy(server);
    SKIPm("Mock server start failed (sockets unavailable?)");
  }
  port = mock_server_get_port(server);

  /* 2. Setup Client (Curl) */
  http_curl_global_init();
  http_client_init(&client);

  rc = http_curl_context_init(&client.transport);
  ASSERT_EQ(0, rc);
  client.send = http_curl_send;

  /* 3. Setup Request */
  http_request_init(&req);
  req.method = HTTP_POST;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  sprintf_s(url, sizeof(url), "http://127.0.0.1:%d/api/curl", port);
#else
  sprintf(url, "http://127.0.0.1:%d/api/curl", port);
#endif
  req.url = (c_cdd_strdup(url, &_ast_strdup_0), _ast_strdup_0);

  http_headers_add(&req.headers, "X-Client", "CDD-Curl");
  req.body = (c_cdd_strdup("payload", &_ast_strdup_1), _ast_strdup_1);
  req.body_len = 7;

  /* 4. Send (Non-blocking from server perspective, but client blocks) */
  /*
     Since the server runs in a thread, we can call send() here.
     send() will return when server replies.
     Server thread will capture request, reply, and signal cond var.
  */

  rc = client.send(client.transport, &req, &res);
  ASSERT_EQ(0, rc);
  ASSERT(res != NULL);
  ASSERT_EQ(200, res->status_code);

  /* 5. Verify Server side capture */
  memset(&captured, 0, sizeof(captured));
  rc = mock_server_wait_for_request(server, &captured);
  ASSERT_EQ(0, rc);
  ASSERT(captured.raw_header != NULL);

  /* Verify Method/URL */
  verify_request_content(&captured, "POST", "/api/curl");

  /* Verify Headers */
  ASSERT(strstr(captured.raw_header, "X-Client: CDD-Curl") != NULL);

  /* Verify Body (at end) */
  ASSERT(strstr(captured.raw_header, "payload") != NULL);

  /* Cleanup */
  mock_server_request_cleanup(&captured);
  http_request_free(&req);
  http_response_free(res);
  free(res);
  http_curl_context_free(client.transport);
  http_client_free(&client);
  http_curl_global_cleanup();
  mock_server_destroy(server);

  PASS();
#else
  SKIPm("Libcurl not supported on this platform");
#endif
}

/* --- WinHTTP Integration --- */

/**
 * @brief Autogenerated docstring
 */
int test_winhttp_transport_integration(TEST *_out_val) {
  char *_ast_strdup_2 = NULL;
  char *_ast_strdup_3 = NULL;
#ifdef _WIN32
  MockServerPtr server;
  struct HttpClient client;
  struct HttpRequest req;
  struct HttpResponse *res = NULL;
  struct MockServerRequest captured;
  int port;
  char url[128];
  int rc;

  /* 1. Start Server */
  mock_server_init(&server);
  ASSERT(server);
  if (mock_server_start(server) != 0) {
    mock_server_destroy(server);
    SKIPm("Mock server start failed (sockets unavailable?)");
  }
  port = mock_server_get_port(server);

  /* 2. Setup Client (WinHTTP) */
  http_winhttp_global_init();
  http_client_init(&client);

  rc = http_winhttp_context_init(&client.transport);
  ASSERT_EQ(0, rc);
  client.send = http_winhttp_send;

  /* 3. Setup Request */
  http_request_init(&req);
  req.method = HTTP_PUT;

  sprintf_s(url, sizeof(url), "http://127.0.0.1:%d/api/win", port);
  req.url = (c_cdd_strdup(url, &_ast_strdup_2), _ast_strdup_2);

  http_headers_add(&req.headers, "X-Client", "CDD-Win");
  http_headers_add(&req.headers, "Content-Length", "4");
  req.body = (c_cdd_strdup("data", &_ast_strdup_3), _ast_strdup_3);
  req.body_len = 4;

  /* 4. Send */
  rc = client.send(client.transport, &req, &res);

  /* Note: WinHTTP might fail on localhost without proper proxy settings or if
     firewall blocks. However, standard loopback should work. */
  ASSERT_EQ(0, rc);
  ASSERT(res != NULL);
  ASSERT_EQ(200, res->status_code);

  /* 5. Verify */
  memset(&captured, 0, sizeof(captured));
  rc = mock_server_wait_for_request(server, &captured);
  ASSERT_EQ(0, rc);

  verify_request_content(&captured, "PUT", "/api/win");
  ASSERT(strstr(captured.raw_header, "X-Client: CDD-Win") != NULL);
  ASSERT(strstr(captured.raw_header, "data") != NULL);

  /* Cleanup */
  mock_server_request_cleanup(&captured);
  http_request_free(&req);
  http_response_free(res);
  free(res);
  http_winhttp_context_free(client.transport);
  http_client_free(&client);
  mock_server_destroy(server);
#else
  SKIPm("WinHTTP not supported on this platform");
#endif
  PASS();
}

int integration_server_suite) {
  RUN_TEST(test_mock_server_lifecycle);
  RUN_TEST(test_curl_transport_integration);
  RUN_TEST(test_winhttp_transport_integration);
}

#endif /* TEST_INTEGRATION_SERVER_H */
