/**
 * @file test_cst2db.h
 * @brief Unit tests for parsing C structs into DB IR.
 */

#ifndef TEST_CST2DB_H
#define TEST_CST2DB_H

#include <greatest.h>
#include <string.h>
#include <stdlib.h>

#include "classes/parse/cst2db.h"
#include "functions/parse/tokenizer.h"
#include "functions/parse/cst.h"

/**
 * @brief Autogenerated docstring
 */
int test_cst2db_basic(TEST *_out_val) {
  const char *src =
      "/** @db */\n"
      "struct User {\n"
      "  /** @primary_key */\n"
      "  int id;\n"
      "  /** @unique */\n"
      "  char *username;\n"
      "  /** @not_null */\n"
      "  int age;\n"
      "};\n";

  struct TokenList *tokens = NULL;
  struct CstNodeList *nodes = NULL;
  struct DatabaseSchema schema;
  int rc;
  
  nodes = calloc(1, sizeof(struct CstNodeList));

  az_span span = az_span_create((uint8_t *)src, strlen(src));
  rc = tokenize(span, &tokens);
  ASSERT_EQ(0, rc);
  
  rc = parse_tokens(tokens, nodes);
  ASSERT_EQ(0, rc);

  db_schema_init(&schema);
  rc = cst_extract_database_schema(nodes, tokens, &schema);
  ASSERT_EQ(0, rc);
  
  if (schema.n_tables != 1) {
    size_t k;
    printf("DEBUG: n_tables=%d\n", (int)schema.n_tables);
    for (k = 0; k < nodes->size; ++k) {
      printf("DEBUG: node %d kind=%d start=%d end=%d\n", (int)k, nodes->nodes[k].kind, (int)nodes->nodes[k].start_token, (int)nodes->nodes[k].end_token);
    }
    for (k = 0; k < tokens->size; ++k) {
      char tmp[100] = {0};
      size_t l = tokens->tokens[k].length < 99 ? tokens->tokens[k].length : 99;
      memcpy(tmp, tokens->tokens[k].start, l);
      printf("DEBUG: tok %d kind=%d str='%s'\n", (int)k, tokens->tokens[k].kind, tmp);
    }
  }
  
  ASSERT_EQ(1, schema.n_tables);
  ASSERT_STR_EQ("User", schema.tables[0].name);
  ASSERT_EQ(3, schema.tables[0].n_columns);
  
  ASSERT_STR_EQ("id", schema.tables[0].columns[0].name);
  ASSERT_EQ(DB_COL_TYPE_INTEGER, schema.tables[0].columns[0].type);
  ASSERT_EQ(1, schema.tables[0].columns[0].is_primary_key);

  ASSERT_STR_EQ("username", schema.tables[0].columns[1].name);
  ASSERT_EQ(DB_COL_TYPE_VARCHAR, schema.tables[0].columns[1].type);
  ASSERT_EQ(1, schema.tables[0].columns[1].is_unique);

  ASSERT_STR_EQ("age", schema.tables[0].columns[2].name);
  ASSERT_EQ(DB_COL_TYPE_INTEGER, schema.tables[0].columns[2].type);
  ASSERT_EQ(0, schema.tables[0].columns[2].is_nullable);

  db_schema_free(&schema);
  free_cst_node_list(nodes);
  free(nodes);
  free_token_list(tokens);
  PASS();
}

/**
 * @brief Autogenerated docstring
 */
int test_cst2db_complex(TEST *_out_val) {
  const char *src =
      "/** @db */\n"
      "struct Post {\n"
      "  /** @primary_key */\n"
      "  int id;\n"
      "  /** @foreign_key */\n"
      "  int user_id;\n"
      "  char *content;\n"
      "};\n";

  struct TokenList *tokens = NULL;
  struct CstNodeList *nodes = NULL;
  struct DatabaseSchema schema;
  int rc;
  
  nodes = calloc(1, sizeof(struct CstNodeList));

  az_span span = az_span_create((uint8_t *)src, strlen(src));
  rc = tokenize(span, &tokens);
  ASSERT_EQ(0, rc);
  
  rc = parse_tokens(tokens, nodes);
  ASSERT_EQ(0, rc);

  db_schema_init(&schema);
  rc = cst_extract_database_schema(nodes, tokens, &schema);
  ASSERT_EQ(0, rc);
  
  if (schema.n_tables != 1) {
    size_t k;
    printf("DEBUG: n_tables=%d\n", (int)schema.n_tables);
    for (k = 0; k < nodes->size; ++k) {
      printf("DEBUG: node %d kind=%d start=%d end=%d\n", (int)k, nodes->nodes[k].kind, (int)nodes->nodes[k].start_token, (int)nodes->nodes[k].end_token);
    }
    for (k = 0; k < tokens->size; ++k) {
      char tmp[100] = {0};
      size_t l = tokens->tokens[k].length < 99 ? tokens->tokens[k].length : 99;
      memcpy(tmp, tokens->tokens[k].start, l);
      printf("DEBUG: tok %d kind=%d str='%s'\n", (int)k, tokens->tokens[k].kind, tmp);
    }
  }
  
  ASSERT_EQ(1, schema.n_tables);
  ASSERT_STR_EQ("Post", schema.tables[0].name);
  ASSERT_EQ(3, schema.tables[0].n_columns);
  
  ASSERT_STR_EQ("id", schema.tables[0].columns[0].name);
  ASSERT_EQ(DB_COL_TYPE_INTEGER, schema.tables[0].columns[0].type);
  ASSERT_EQ(1, schema.tables[0].columns[0].is_primary_key);

  ASSERT_STR_EQ("user_id", schema.tables[0].columns[1].name);
  ASSERT_EQ(DB_COL_TYPE_INTEGER, schema.tables[0].columns[1].type);
  ASSERT_STR_EQ("unknown_ref", schema.tables[0].columns[1].foreign_key_table);
  ASSERT_STR_EQ("id", schema.tables[0].columns[1].foreign_key_column);

  db_schema_free(&schema);
  free_cst_node_list(nodes);
  free(nodes);
  free_token_list(tokens);
  PASS();
}

int cst2db_suite) {
  RUN_TEST(test_cst2db_basic);
  RUN_TEST(test_cst2db_complex);
}

#endif /* TEST_CST2DB_H */
