/* clang-format off */
#include "cdd_ffi_emit_python.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c_cdd/safe_crt.h"
/* clang-format on */

/**
 * @brief Emits Python ctypes wrapper for a specific C primitive type.
 */
static const char *get_ctypes_primitive(cdd_ffi_primitive_kind_t kind) {
  switch (kind) {
  case CDD_FFI_KIND_VOID:
    return "None";
  case CDD_FFI_KIND_BOOL:
    return "ctypes.c_bool";
  case CDD_FFI_KIND_INT8:
    return "ctypes.c_int8";
  case CDD_FFI_KIND_UINT8:
    return "ctypes.c_uint8";
  case CDD_FFI_KIND_INT16:
    return "ctypes.c_int16";
  case CDD_FFI_KIND_UINT16:
    return "ctypes.c_uint16";
  case CDD_FFI_KIND_INT32:
    return "ctypes.c_int32";
  case CDD_FFI_KIND_UINT32:
    return "ctypes.c_uint32";
  case CDD_FFI_KIND_INT64:
    return "ctypes.c_int64";
  case CDD_FFI_KIND_UINT64:
    return "ctypes.c_uint64";
  case CDD_FFI_KIND_FLOAT32:
    return "ctypes.c_float";
  case CDD_FFI_KIND_FLOAT64:
    return "ctypes.c_double";
  case CDD_FFI_KIND_OPAQUE_PTR:
    return "ctypes.c_void_p";
  case CDD_FFI_KIND_FUNCTION_PTR:
    return "ctypes.c_void_p";
  default:
    return "ctypes.c_void_p";
  }
}

static void emit_type(FILE *f, const cdd_ffi_type_t *type) {
  if (type->pointer_depth > 0) {
    cdd_ffi_type_t sub_type;
    if (type->kind == CDD_FFI_KIND_INT8 || type->kind == CDD_FFI_KIND_UINT8 ||
        type->kind == CDD_FFI_KIND_VOID) {
      if (type->pointer_depth == 1) {
        fprintf(f, "ctypes.c_void_p");
        return;
      }
    }
    /* Simplistic pointer representation */
    fprintf(f, "ctypes.POINTER(");
    sub_type = *type;
    sub_type.pointer_depth--;
    emit_type(f, &sub_type);
    fprintf(f, ")");
    return;
  }

  if (type->ref_name) {
    if (type->kind == CDD_FFI_KIND_STRUCT_REF ||
        type->kind == CDD_FFI_KIND_ENUM_REF) {
      fprintf(f, "%s", type->ref_name);
    } else {
      fprintf(f, "%s", type->ref_name);
    }
    return;
  }

  fprintf(f, "%s", get_ctypes_primitive(type->kind));
}

enum cdd_c_error
cdd_ffi_emit_python(cdd_ffi_ir_t *ir,
                    const cdd_generate_bindings_config_t *config) {
  FILE *f;
  size_t i, j;
  char filepath[1024];

  if (!ir || !config || !config->output_dir) {
    return CDD_C_ERROR_INVALID_ARGUMENT;
  }

  /* Use safe CRT if available */
#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\cdd_bindings.py",
            config->output_dir);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/cdd_bindings.py",
               config->output_dir);
  f = fopen(filepath, "w");
#endif

  {
    extern volatile int g_fail_io_after;
    if (g_fail_io_after == 1) {
      if (f)
        fclose(f);
      f = NULL;
    }
  }

  if (!f)
    return CDD_C_ERROR_IO;

  fprintf(f, "# Auto-generated by cdd-c\n");
  fprintf(f, "import ctypes\n");
  fprintf(f, "import sys\n");
  fprintf(f, "import os\n\n");

  /* Basic dll loader */
  fprintf(f, "def _load_library():\n");
  fprintf(f, "    lib_name = '%s'\n",
          config->library_name ? config->library_name : "libname");
  fprintf(f, "    if sys.platform == 'win32':\n");
  fprintf(f, "        lib_ext = '.dll'\n");
  fprintf(f, "    elif sys.platform == 'darwin':\n");
  fprintf(f, "        lib_ext = '.dylib'\n");
  fprintf(f, "    else:\n");
  fprintf(f, "        lib_ext = '.so'\n");
  fprintf(f, "        if not lib_name.startswith('lib'):\n");
  fprintf(f, "            lib_name = 'lib' + lib_name\n");
  fprintf(f, "    \n");
  fprintf(f,
          "    # Attempt to load from current directory first, then system\n");
  fprintf(f, "    paths = [os.path.join(os.path.dirname(__file__), lib_name + "
             "lib_ext), lib_name + lib_ext]\n");
  fprintf(f, "    for path in paths:\n");
  fprintf(f, "        try:\n");
  fprintf(f, "            return ctypes.CDLL(path)\n");
  fprintf(f, "        except OSError:\n");
  fprintf(f, "            pass\n");
  fprintf(f, "    raise OSError(f\"Could not load shared library "
             "{lib_name}{lib_ext}\")\n\n");

  fprintf(f, "lib = _load_library()\n\n");

  fprintf(f, "class CddFfiError(ctypes.Structure):\n");
  fprintf(f, "    _fields_ = [\n");
  fprintf(f, "        ('code', ctypes.c_int),\n");
  fprintf(f, "        ('message', ctypes.c_char_p)\n");
  fprintf(f, "    ]\n\n");

  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];

    if (node->kind == CDD_FFI_NODE_MACRO) {
      if (node->evaluated_value) {
        if (node->inferred_type == CDD_FFI_MACRO_TYPE_STRING) {
          fprintf(f, "%s = %s\n\n", node->name,
                  node->evaluated_value); /* string already has quotes? Wait,
                                             the lexer removes them? No, lexer
                                             keeps "..."? Let's assume
                                             evaluated_value is the string */
        } else {
          fprintf(f, "%s = %s\n\n", node->name, node->evaluated_value);
        }
      }
    } else if (node->kind == CDD_FFI_NODE_ENUM) {
      fprintf(f, "class %s(ctypes.c_int):\n", node->name);
      if (node->variants_count == 0) {
        fprintf(f, "    pass\n");
      }
      for (j = 0; j < node->variants_count; j++) {
        fprintf(f, "    %s = %s\n", node->variants[j].name,
                node->variants[j].value ? node->variants[j].value : "0");
      }
      fprintf(f, "\n");
    } else if (node->kind == CDD_FFI_NODE_STRUCT ||
               node->kind == CDD_FFI_NODE_UNION) {
      fprintf(f, "class %s(%s):\n", node->name,
              node->kind == CDD_FFI_NODE_STRUCT ? "ctypes.Structure"
                                                : "ctypes.Union");
      if (node->fields_count == 0) {
        fprintf(f, "    _fields_ = []\n");
      } else {
        fprintf(f, "    _fields_ = [\n");
        for (j = 0; j < node->fields_count; j++) {
          fprintf(f, "        (\"%s\", ", node->fields[j].name);
          emit_type(f, &node->fields[j].type);
          fprintf(f, "),\n");
        }
        fprintf(f, "    ]\n");
      }

      if (strstr(node->name, "_Trampoline")) {
        fprintf(f, "\n    def __init__(self, target_obj):\n");
        fprintf(f, "        super().__init__()\n");
        fprintf(f, "        self._target = target_obj\n");
        fprintf(f, "        self.target_lang_ctx = "
                   "ctypes.cast(ctypes.pointer(ctypes.py_object(target_obj)), "
                   "ctypes.c_void_p)\n");
        for (j = 3; j < node->fields_count; j++) {
          const char *fn_name = node->fields[j].name + 3; /* skip cb_ */
          fprintf(f, "        if hasattr(target_obj, '%s'):\n", fn_name);
          fprintf(f, "            cb_type = ctypes.CFUNCTYPE(None, "
                     "ctypes.c_void_p)\n");
          fprintf(f,
                  "            self._%s_cb = cb_type(lambda ctx: "
                  "target_obj.%s())\n",
                  fn_name, fn_name);
          fprintf(f,
                  "            self.%s = ctypes.cast(self._%s_cb, "
                  "ctypes.c_void_p)\n",
                  node->fields[j].name, fn_name);
        }
        fprintf(f, "        pass\n\n");
      }

      if (node->base_classes_count > 0) {
        fprintf(f, "    \n");
        for (j = 0; j < node->base_classes_count; j++) {
          fprintf(f, "    def as_%s(self):\n", node->base_classes[j].name);
          fprintf(f, "        func = getattr(lib, '%s_upcast_to_%s', None)\n",
                  node->name, node->base_classes[j].name);
          fprintf(f, "        if func:\n");
          fprintf(f,
                  "            func.argtypes = [ctypes.POINTER(%s), "
                  "ctypes.POINTER(CddFfiError)]\n",
                  node->name);
          fprintf(f, "            func.restype = ctypes.POINTER(%s)\n",
                  node->base_classes[j].name);
          fprintf(f, "            err = CddFfiError()\n");
          fprintf(f, "            res = func(ctypes.pointer(self), "
                     "ctypes.byref(err))\n");
          fprintf(f, "            if err.code != 0:\n");
          fprintf(
              f,
              "                raise RuntimeError(err.message.decode('utf-8') "
              "if err.message else 'Unknown native error')\n");
          fprintf(f, "            return res.contents if res else None\n");
          fprintf(f, "        return None\n");
        }
      }
      fprintf(f, "\n");
    } else if (node->kind == CDD_FFI_NODE_FUNCTION) {
      fprintf(f, "try:\n");
      fprintf(f, "    _%s = getattr(lib, '%s')\n", node->name, node->name);

      /* args */
      fprintf(f, "    _%s.argtypes = [", node->name);
      for (j = 0; j < node->fields_count; j++) {
        emit_type(f, &node->fields[j].type);
        fprintf(f, ", ");
      }
      fprintf(f, "ctypes.POINTER(CddFfiError)]\n");

      /* return type */
      fprintf(f, "    _%s.restype = ", node->name);
      emit_type(f, &node->return_or_base_type);
      fprintf(f, "\n");

      if (node->is_variadic) {
        fprintf(f, "    def %s(", node->name);
        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent != CDD_FFI_INTENT_OUT) {
            const char *arg_name =
                node->fields[j].name ? node->fields[j].name : "arg";
            fprintf(f, "%s, ", arg_name);
          }
        }
        fprintf(f, "*args):\n");

        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
              node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
            cdd_ffi_type_t base_t;
            fprintf(f, "        out_%s = ", node->fields[j].name);
            base_t = node->fields[j].type;
            if (base_t.pointer_depth > 0)
              base_t.pointer_depth--;
            emit_type(f, &base_t);
            fprintf(f, "()\n");
          }
        }

        fprintf(f, "        err = CddFfiError()\n");
        fprintf(f, "        res = _%s(", node->name);
        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
              node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
            fprintf(f, "ctypes.byref(out_%s), ", node->fields[j].name);
          } else {
            const char *arg_name =
                node->fields[j].name ? node->fields[j].name : "arg";
            fprintf(f, "%s, ", arg_name);
          }
        }
        fprintf(f, "*args, ctypes.byref(err))\n");
      } else {
        /* Wrapper function */
        int first_arg = 1;
        fprintf(f, "    def %s(", node->name);
        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent != CDD_FFI_INTENT_OUT) {
            const char *arg_name =
                node->fields[j].name ? node->fields[j].name : "arg";
            if (!first_arg)
              fprintf(f, ", ");
            fprintf(f, "%s", arg_name);
            first_arg = 0;
          }
        }
        fprintf(f, "):\n");

        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
              node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
            if (node->fields[j].array_length_ref) {
              cdd_ffi_type_t base_t;
              fprintf(f, "        out_%s = (", node->fields[j].name);
              base_t = node->fields[j].type;
              if (base_t.pointer_depth > 0)
                base_t.pointer_depth--;
              emit_type(f, &base_t);
              fprintf(f, " * %s)()\n", node->fields[j].array_length_ref);
            } else {
              cdd_ffi_type_t base_t;
              fprintf(f, "        out_%s = ", node->fields[j].name);
              base_t = node->fields[j].type;
              if (base_t.pointer_depth > 0)
                base_t.pointer_depth--;
              emit_type(f, &base_t);
              fprintf(f, "()\n");
            }
            if (node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
              fprintf(f, "        out_%s.value = %s\n", node->fields[j].name,
                      node->fields[j].name);
            }
          }
        }

        fprintf(f, "        err = CddFfiError()\n");
        fprintf(f, "        res = _%s(", node->name);
        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
              node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
            fprintf(f, "ctypes.byref(out_%s), ", node->fields[j].name);
          } else {
            const char *arg_name =
                node->fields[j].name ? node->fields[j].name : "arg";
            fprintf(f, "%s, ", arg_name);
          }
        }
        fprintf(f, "ctypes.byref(err))\n");
      }
      fprintf(f, "        if err.code != 0:\n");
      fprintf(f, "            raise RuntimeError(err.message.decode('utf-8') "
                 "if err.message else 'Unknown native error')\n");

      /* Collect Out Params for return tuple */
      {
        int out_count = 0;
        for (j = 0; j < node->fields_count; j++) {
          if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
              node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
            out_count++;
          }
        }
        if (out_count > 0) {
          fprintf(f, "        return (");
          if (node->return_or_base_type.kind != CDD_FFI_KIND_VOID) {
            fprintf(f, "res, ");
          }
          for (j = 0; j < node->fields_count; j++) {
            if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
                node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
              if (node->fields[j].array_length_ref) {
                fprintf(f, "list(out_%s), ", node->fields[j].name);
              } else {
                fprintf(f, "out_%s.value, ", node->fields[j].name);
              }
            }
          }
          fprintf(f, ")\n\n");
        } else {
          fprintf(f, "        return res\n\n");
        }
      }

      fprintf(f, "except AttributeError:\n");
      fprintf(f, "    pass\n\n");
    }
  }

  fclose(f);

  /* Generate Python C API Wrapper (cdd_python_wrap.c) for GIL handling */
  {
    FILE *fc;
#if defined(_MSC_VER)
    sprintf_s(filepath, sizeof(filepath), "%s\\cdd_python_wrap.c",
              config->output_dir);
    fopen_s(&fc, filepath, "w");
#else
    CDD_SNPRINTF(filepath, sizeof(filepath), "%s/cdd_python_wrap.c",
                 config->output_dir);
    fc = fopen(filepath, "w");
#endif
    {
      extern volatile int g_fail_io_after;
      if (g_fail_io_after == 2) {
        if (fc)
          fclose(fc);
        fc = NULL;
      }
    }
    if (fc) {
      fprintf(fc, "/* Auto-generated Python C API Wrapper */\n");
      fprintf(fc, "#define PY_SSIZE_T_CLEAN\n");
      fprintf(fc, "#include <Python.h>\n\n");

      for (i = 0; i < ir->nodes_count; i++) {
        cdd_ffi_ir_node_t *node = &ir->nodes[i];
        if (node->kind == CDD_FFI_NODE_FUNCTION && node->requires_gil_release) {
          fprintf(
              fc,
              "static PyObject* wrap_%s(PyObject* self, PyObject* args) {\n",
              node->name);
          fprintf(fc, "    /* Parse args... (omitted for brevity) */\n");
          fprintf(fc, "    Py_BEGIN_ALLOW_THREADS\n");
          fprintf(fc, "    /* %s(); */\n", node->name);
          fprintf(fc, "    Py_END_ALLOW_THREADS\n");
          fprintf(fc, "    Py_RETURN_NONE;\n");
          fprintf(fc, "}\n\n");
        }
      }
      fclose(fc);
    }
  }

  if (config->generate_tests) {
#if defined(_MSC_VER)
    sprintf_s(filepath, sizeof(filepath), "%s\\test_cdd_bindings.py",
              config->output_dir);
    fopen_s(&f, filepath, "w");
#else
    CDD_SNPRINTF(filepath, sizeof(filepath), "%s/test_cdd_bindings.py",
                 config->output_dir);
    f = fopen(filepath, "w");
#endif
    {
      extern volatile int g_fail_io_after;
      if (g_fail_io_after == 3) {
        if (f)
          fclose(f);
        f = NULL;
      }
    }
    if (f) {
      fprintf(f, "# Auto-generated pytest harness for cdd-c bindings\n");
      fprintf(f, "import pytest\n");
      fprintf(f, "import cdd_bindings\n\n");
      fprintf(f, "def test_library_loaded():\n");
      fprintf(f, "    assert cdd_bindings.lib is not None\n\n");

      for (i = 0; i < ir->nodes_count; i++) {
        cdd_ffi_ir_node_t *node = &ir->nodes[i];
        if (node->kind == CDD_FFI_NODE_STRUCT ||
            node->kind == CDD_FFI_NODE_UNION) {
          fprintf(f, "def test_%s_exists():\n", node->name);
          fprintf(f, "    assert hasattr(cdd_bindings, '%s')\n", node->name);
          fprintf(f, "    obj = cdd_bindings.%s()\n", node->name);
          fprintf(f, "    assert obj is not None\n\n");
        } else if (node->kind == CDD_FFI_NODE_FUNCTION) {
          int out_count = 0;
          for (j = 0; j < node->fields_count; j++) {
            if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
                node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
              out_count++;
            }
          }
          fprintf(f, "def test_%s_exists():\n", node->name);
          fprintf(f, "    assert hasattr(cdd_bindings, '%s')\n", node->name);
          if (out_count > 0) {
            fprintf(f, "    # Multiple return values test\n");
            fprintf(f, "    # result = cdd_bindings.%s(...)\n", node->name);
            fprintf(f, "    # assert isinstance(result, tuple)\n");
          }
          fprintf(f, "\n");
        }
      }
      fclose(f);
    }
  }

  return CDD_C_SUCCESS;
}
