/* clang-format off */
#include "cdd_ffi_emit_rust.h"
#include "../parse/fs.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c_cdd/safe_crt.h"
/* clang-format on */

static const char *get_rust_primitive(cdd_ffi_primitive_kind_t kind) {
  switch (kind) {
    /* LCOV_EXCL_START */
  case CDD_FFI_KIND_VOID:
    return "std::ffi::c_void";
    /* LCOV_EXCL_STOP */
  case CDD_FFI_KIND_BOOL:
    return "bool";
  case CDD_FFI_KIND_INT8:
    return "i8";
  case CDD_FFI_KIND_UINT8:
    return "u8";
  case CDD_FFI_KIND_INT16:
    return "i16";
  case CDD_FFI_KIND_UINT16:
    return "u16";
  case CDD_FFI_KIND_INT32:
    return "i32";
  case CDD_FFI_KIND_UINT32:
    return "u32";
  case CDD_FFI_KIND_INT64:
    return "i64";
  case CDD_FFI_KIND_UINT64:
    return "u64";
  case CDD_FFI_KIND_FLOAT32:
    return "f32";
  case CDD_FFI_KIND_FLOAT64:
    return "f64";
  case CDD_FFI_KIND_OPAQUE_PTR:
    return "std::ffi::c_void";
  case CDD_FFI_KIND_FUNCTION_PTR:
    return "std::ffi::c_void";
  default:
    return "std::ffi::c_void";
  }
}

static void emit_rust_sys_type(FILE *f, const cdd_ffi_type_t *type,
                               int is_return) {
  if (type->kind == CDD_FFI_KIND_VOID && type->pointer_depth == 0) {
    if (is_return) {
      fprintf(f, "()");
    } else {
      fprintf(f, "std::ffi::c_void");
    }
    return;
  }

  if (type->pointer_depth > 0) {
    cdd_ffi_type_t sub_type;
    int pd;
    for (pd = 0; pd < type->pointer_depth; pd++) {
      if (type->is_const && pd == 0) {
        fprintf(f, "*const ");
      } else {
        fprintf(f, "*mut ");
      }
    }
    sub_type = *type;
    sub_type.pointer_depth = 0;
    sub_type.is_const = 0;
    emit_rust_sys_type(f, &sub_type, 0);
    return;
  }

  if (type->ref_name) {
    fprintf(f, "%s", type->ref_name);
    return;
  }

  fprintf(f, "%s", get_rust_primitive(type->kind));
}

static enum cdd_c_error emit_sys_rs(cdd_ffi_ir_t *ir, const char *dir_path) {
  FILE *f;
  char filepath[1024];
  size_t i, j;

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\src\\sys.rs", dir_path);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/src/sys.rs", dir_path);
  f = fopen(filepath, "w");
#endif

  if (!f)
    /* LCOV_EXCL_START */
    return CDD_C_ERROR_IO;
  /* LCOV_EXCL_STOP */

  fprintf(f, "/* Auto-generated by cdd-c */\n");
  fprintf(f, "#![allow(non_camel_case_types)]\n");
  fprintf(f, "#![allow(non_snake_case)]\n");
  fprintf(f, "#![allow(dead_code)]\n\n");

  /* Enums, Structs, Typedefs */
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_STRUCT || node->kind == CDD_FFI_NODE_UNION) {
      fprintf(f, "#[repr(C)]\n");
      fprintf(f, "#[derive(Debug, Copy, Clone)]\n");
      fprintf(f, "pub %s %s {\n",
              node->kind == CDD_FFI_NODE_UNION ? "union" : "struct",
              node->name);
      for (j = 0; j < node->fields_count; j++) {
        fprintf(f, "    pub %s: ", node->fields[j].name);
        emit_rust_sys_type(f, &node->fields[j].type, 0);
        fprintf(f, ",\n");
      }
      fprintf(f, "}\n\n");
    } else if (node->kind == CDD_FFI_NODE_ENUM) {
      fprintf(f, "pub type %s = std::os::raw::c_int;\n", node->name);
      for (j = 0; j < node->variants_count; j++) {
        fprintf(f, "pub const %s: %s = %s;\n", node->variants[j].name,
                node->name,
                node->variants[j].value ? node->variants[j].value : "0");
      }
      fprintf(f, "\n");
    } else if (node->kind == CDD_FFI_NODE_TYPEDEF) {
      fprintf(f, "pub type %s = ", node->name);
      emit_rust_sys_type(f, &node->return_or_base_type, 0);
      fprintf(f, ";\n\n");
    }
  }

  /* Functions */
  fprintf(f, "extern \"C\" {\n");
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_FUNCTION) {
      fprintf(f, "    pub fn %s(", node->name);
      for (j = 0; j < node->fields_count; j++) {
        fprintf(f, "%s: ", node->fields[j].name);
        emit_rust_sys_type(f, &node->fields[j].type, 0);
        if (j < node->fields_count - 1)
          fprintf(f, ", ");
      }
      if (node->fields_count > 0)
        fprintf(f, ", ");
      fprintf(f, "err: *mut CddFfiError) -> ");
      emit_rust_sys_type(f, &node->return_or_base_type, 1);
      fprintf(f, ";\n");
    }
  }
  fprintf(f, "}\n");

  fclose(f);
  return CDD_C_SUCCESS;
}

static enum cdd_c_error emit_lib_rs(cdd_ffi_ir_t *ir, const char *dir_path) {
  FILE *f;
  char filepath[1024];
  size_t i;

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\src\\lib.rs", dir_path);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/src/lib.rs", dir_path);
  f = fopen(filepath, "w");
#endif

  if (!f)
    /* LCOV_EXCL_START */
    return CDD_C_ERROR_IO;
  /* LCOV_EXCL_STOP */

  fprintf(f, "/* Auto-generated by cdd-c */\n");
  fprintf(f, "pub mod sys;\n\n");
  fprintf(f, "pub use sys::*;\n\n");

  fprintf(f, "use std::ffi::CStr;\n");
  fprintf(f, "use std::ffi::CString;\n");
  fprintf(f, "use std::os::raw::c_char;\n\n");

  fprintf(f, "#[derive(Debug)]\n");
  fprintf(f, "pub struct FfiError {\n");
  fprintf(f, "    pub code: i32,\n");
  fprintf(f, "    pub message: String,\n");
  fprintf(f, "}\n\n");

  fprintf(f, "impl std::fmt::Display for FfiError {\n");
  fprintf(f, "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> "
             "std::fmt::Result {\n");
  fprintf(f,
          "        write!(f, \"FfiError({}): {}\", self.code, self.message)\n");
  fprintf(f, "    }\n");
  fprintf(f, "}\n\n");

  fprintf(f, "impl std::error::Error for FfiError {}\n\n");

  /* Safe functions struct wrapper */
  fprintf(f, "pub struct Wrapper;\n\n");
  fprintf(f, "impl Wrapper {\n");
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_FUNCTION) {
      size_t j;
      fprintf(f, "    pub fn %s_safe(", node->name);
      for (j = 0; j < node->fields_count; j++) {
        fprintf(f, "%s: ", node->fields[j].name);
        /* If it's a pointer to i8/u8, use &std::ffi::CStr for idiomatic rust */
        if (node->fields[j].type.pointer_depth == 1 &&
            (node->fields[j].type.kind == CDD_FFI_KIND_INT8 ||
             node->fields[j].type.kind == CDD_FFI_KIND_UINT8)) {
          fprintf(f, "&std::ffi::CStr");
        } else {
          emit_rust_sys_type(f, &node->fields[j].type, 0);
        }
        if (j < node->fields_count - 1)
          fprintf(f, ", ");
      }
      fprintf(f, ") -> Result<");
      emit_rust_sys_type(f, &node->return_or_base_type, 1);
      fprintf(f, ", FfiError> {\n");

      fprintf(f, "        let mut err = sys::CddFfiError {\n");
      fprintf(f, "            code: 0,\n");
      fprintf(f, "            message: std::ptr::null_mut(),\n");
      fprintf(f, "        };\n");

      fprintf(f, "        let res = unsafe { sys::%s(", node->name);
      for (j = 0; j < node->fields_count; j++) {
        if (node->fields[j].type.pointer_depth == 1 &&
            (node->fields[j].type.kind == CDD_FFI_KIND_INT8 ||
             node->fields[j].type.kind == CDD_FFI_KIND_UINT8)) {
          fprintf(f, "%s.as_ptr()", node->fields[j].name);
        } else {
          fprintf(f, "%s", node->fields[j].name);
        }
        fprintf(f, ", ");
      }
      fprintf(f, "&mut err as *mut sys::CddFfiError) };\n");

      fprintf(f, "        if err.code != 0 {\n");
      fprintf(f, "            let msg = if !err.message.is_null() {\n");
      fprintf(f, "                unsafe { CStr::from_ptr(err.message as "
                 "*const c_char).to_string_lossy().into_owned() }\n");
      fprintf(f, "            } else {\n");
      fprintf(f, "                \"Unknown native error\".to_string()\n");
      fprintf(f, "            };\n");
      fprintf(f, "            Err(FfiError { code: err.code as i32, message: "
                 "msg })\n");
      fprintf(f, "        } else {\n");
      fprintf(f, "            Ok(res)\n");
      fprintf(f, "        }\n");

      fprintf(f, "    }\n");
    }
  }
  fprintf(f, "}\n");

  fclose(f);
  return CDD_C_SUCCESS;
}

static enum cdd_c_error
emit_cargo_toml(const cdd_generate_bindings_config_t *config) {
  FILE *f;
  char filepath[1024];

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\Cargo.toml", config->output_dir);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/Cargo.toml", config->output_dir);
  f = fopen(filepath, "w");
#endif

  if (!f)
    return CDD_C_ERROR_IO;

  fprintf(f, "[package]\n");
  fprintf(f, "name = \"%s-bindings\"\n",
          config->library_name ? config->library_name : "libname");
  fprintf(f, "version = \"0.1.0\"\n");
  fprintf(f, "edition = \"2021\"\n\n");
  fprintf(f, "[dependencies]\n");
  /* if we used libc crate we'd add it here */
  fprintf(f, "libc = \"0.2\"\n");

  fclose(f);
  return CDD_C_SUCCESS;
}

static enum cdd_c_error
emit_integration_tests(cdd_ffi_ir_t *ir,
                       const cdd_generate_bindings_config_t *config) {
  FILE *f;
  char filepath[1024];
  size_t i;

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\tests\\integration_test.rs",
            config->output_dir);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/tests/integration_test.rs",
               config->output_dir);
  f = fopen(filepath, "w");
#endif

  if (!f)
    /* LCOV_EXCL_START */
    return CDD_C_ERROR_IO;
  /* LCOV_EXCL_STOP */

  fprintf(f, "use %s_bindings::*;\n\n",
          config->library_name ? config->library_name : "libname");
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_STRUCT || node->kind == CDD_FFI_NODE_UNION) {
      fprintf(f, "#[test]\n");
      fprintf(f, "fn test_%s_size() {\n", node->name);
      fprintf(f, "    assert!(std::mem::size_of::<%s>() > 0);\n", node->name);
      fprintf(f, "}\n\n");
    }
  }

  fclose(f);
  return CDD_C_SUCCESS;
}

enum cdd_c_error
cdd_ffi_emit_rust(cdd_ffi_ir_t *ir,
                  const cdd_generate_bindings_config_t *config) {
  int rc;
  char src_dir[1024];
  char tests_dir[1024];

  if (!ir || !config || !config->output_dir)
    return CDD_C_ERROR_INVALID_ARGUMENT;

#if defined(_MSC_VER)
  sprintf_s(src_dir, sizeof(src_dir), "%s\\src", config->output_dir);
  sprintf_s(tests_dir, sizeof(tests_dir), "%s\\tests", config->output_dir);
#else
  CDD_SNPRINTF(src_dir, sizeof(src_dir), "%s/src", config->output_dir);
  CDD_SNPRINTF(tests_dir, sizeof(tests_dir), "%s/tests", config->output_dir);
#endif

  makedir(src_dir);
  makedir(tests_dir);

  rc = emit_cargo_toml(config);
  if (rc != 0)
    return rc;

  rc = emit_sys_rs(ir, config->output_dir);
  if (rc != 0)
    /* LCOV_EXCL_START */
    return rc;
  /* LCOV_EXCL_STOP */

  rc = emit_lib_rs(ir, config->output_dir);
  if (rc != 0)
    /* LCOV_EXCL_START */
    return rc;
  /* LCOV_EXCL_STOP */

  if (config->generate_tests) {
    rc = emit_integration_tests(ir, config);
    if (rc != 0)
      /* LCOV_EXCL_START */
      return rc;
    /* LCOV_EXCL_STOP */
  }

  return CDD_C_SUCCESS;
}
