/* clang-format off */
#include "cdd_ffi_emit_csharp.h"
#include "../parse/fs.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c_cdd/safe_crt.h"
/* clang-format on */

static const char *get_csharp_primitive(cdd_ffi_primitive_kind_t kind) {
  switch (kind) {
  case CDD_FFI_KIND_BOOL:
    return "byte";
  case CDD_FFI_KIND_INT8:
    return "sbyte";
  case CDD_FFI_KIND_UINT8:
    return "byte";
  case CDD_FFI_KIND_INT16:
    return "short";
  case CDD_FFI_KIND_UINT16:
    return "ushort";
  case CDD_FFI_KIND_INT32:
    return "int";
  case CDD_FFI_KIND_UINT32:
    return "uint";
  case CDD_FFI_KIND_INT64:
    return "long";
  case CDD_FFI_KIND_UINT64:
    return "ulong";
  case CDD_FFI_KIND_FLOAT32:
    return "float";
  case CDD_FFI_KIND_FLOAT64:
    return "double";
  case CDD_FFI_KIND_OPAQUE_PTR:
    return "IntPtr";
  case CDD_FFI_KIND_FUNCTION_PTR:
    return "IntPtr";
  default:
    return "IntPtr";
  }
}

static void emit_csharp_type(FILE *f, const cdd_ffi_type_t *type,
                             int is_return) {
  if (type->kind == CDD_FFI_KIND_VOID && type->pointer_depth == 0) {
    if (is_return) {
      fprintf(f, "void");
    } else {
      fprintf(f, "IntPtr");
    }
    return;
  }

  if (type->pointer_depth > 0) {
    if (type->pointer_depth == 1 &&
        (type->kind == CDD_FFI_KIND_INT8 || type->kind == CDD_FFI_KIND_UINT8 ||
         type->kind == CDD_FFI_KIND_VOID)) {
      /* String representation could be handled via MarshalAs LPStr, but
       * generally IntPtr is safest for raw pointers */
      fprintf(f, "IntPtr");
      return;
    }
    if (type->pointer_depth == 1 && type->ref_name &&
        type->kind == CDD_FFI_KIND_STRUCT_REF) {
      fprintf(f, "ref %s", type->ref_name);
      return;
    }
    fprintf(f, "IntPtr");
    return;
  }

  if (type->ref_name) {
    fprintf(f, "%s", type->ref_name);
    return;
  }

  fprintf(f, "%s", get_csharp_primitive(type->kind));
}

static enum cdd_c_error
emit_csharp_bindings(cdd_ffi_ir_t *ir,
                     const cdd_generate_bindings_config_t *config) {
  FILE *f;
  char filepath[1024];
  size_t i, j;
  extern volatile int g_fail_io_after;
  const char *libname = config->library_name ? config->library_name : "libname";

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\Bindings.cs", config->output_dir);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/Bindings.cs",
               config->output_dir);
  f = fopen(filepath, "w");
#endif

  if (g_fail_io_after == 555) {
    if (f) {
      fclose(f);
      f = NULL;
    }
  }

  if (!f)
    return CDD_C_ERROR_IO;

  fprintf(f, "// Auto-generated by cdd-c\n");
  fprintf(f, "using System;\n");
  fprintf(f, "using System.Runtime.InteropServices;\n\n");
  fprintf(f, "namespace %sBindings\n{\n", libname);

  /* Enums */
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_ENUM) {
      fprintf(f, "    public enum %s : int\n    {\n", node->name);
      for (j = 0; j < node->variants_count; j++) {
        fprintf(f, "        %s = %s,\n", node->variants[j].name,
                node->variants[j].value ? node->variants[j].value : "0");
      }
      fprintf(f, "    }\n\n");
    }
  }

  /* Structs */
  /* Emit Interfaces for base classes */
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_STRUCT) {
      int has_derived = 0;
      size_t k, b;
      for (k = 0; k < ir->nodes_count; k++) {
        if (ir->nodes[k].kind == CDD_FFI_NODE_STRUCT) {
          for (b = 0; b < ir->nodes[k].base_classes_count; b++) {
            if (strcmp(ir->nodes[k].base_classes[b].name, node->name) == 0) {
              has_derived = 1;
              break;
            }
          }
        }
        if (has_derived)
          break;
      }
      if (has_derived || node->base_classes_count > 0) {
        fprintf(f, "    public interface I%s {\n", node->name);
        fprintf(f, "        IntPtr GetPointer();\n");
        fprintf(f, "    }\n\n");
      }
    }
  }

  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_STRUCT || node->kind == CDD_FFI_NODE_UNION) {
      fprintf(f, "    [StructLayout(LayoutKind.%s)]\n",
              node->kind == CDD_FFI_NODE_UNION ? "Explicit" : "Sequential");
      fprintf(f, "    public struct %s ", node->name);
      if (node->base_classes_count > 0) {
        fprintf(f, ": ");
        for (j = 0; j < node->base_classes_count; j++) {
          fprintf(f, "I%s", node->base_classes[j].name);
          if (j < node->base_classes_count - 1)
            fprintf(f, ", ");
        }
        fprintf(f, "\n    {\n");
      } else {
        fprintf(f, "\n    {\n");
      }
      for (j = 0; j < node->fields_count; j++) {
        if (node->kind == CDD_FFI_NODE_UNION) {
          fprintf(f, "        [FieldOffset(0)]\n");
        }
        fprintf(f, "        public ");
        emit_csharp_type(f, &node->fields[j].type, 0);
        fprintf(f, " %s;\n", node->fields[j].name);
      }
      fprintf(f, "    }\n\n");
    }
  }

  /* Functions */
  fprintf(f, "    public static class NativeMethods\n    {\n");
  fprintf(f, "        public const string LibraryName = \"%s\";\n\n", libname);
  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_FUNCTION) {
      fprintf(f, "        [DllImport(LibraryName, CallingConvention = "
                 "CallingConvention.Cdecl)]\n");

      /* Special MarshalAs for strings if returning char* */
      if (node->return_or_base_type.pointer_depth == 1 &&
          (node->return_or_base_type.kind == CDD_FFI_KIND_INT8 ||
           node->return_or_base_type.kind == CDD_FFI_KIND_UINT8)) {
        fprintf(f, "        [return: MarshalAs(UnmanagedType.LPStr)]\n");
      }

      fprintf(f, "        public static extern ");
      emit_csharp_type(f, &node->return_or_base_type, 1);
      fprintf(f, " %s(", node->name);

      for (j = 0; j < node->fields_count; j++) {
        if (node->fields[j].intent == CDD_FFI_INTENT_OUT) {
          fprintf(f, "out ");
        } else if (node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
          fprintf(f, "ref ");
        }

        if (node->fields[j].type.pointer_depth == 1 &&
            (node->fields[j].type.kind == CDD_FFI_KIND_INT8 ||
             node->fields[j].type.kind == CDD_FFI_KIND_UINT8)) {
          fprintf(f, "[MarshalAs(UnmanagedType.LPStr)] string ");
        } else {
          cdd_ffi_type_t base_t = node->fields[j].type;
          if (node->fields[j].intent == CDD_FFI_INTENT_OUT ||
              node->fields[j].intent == CDD_FFI_INTENT_INOUT) {
            if (base_t.pointer_depth > 0)
              base_t.pointer_depth--;
          }
          emit_csharp_type(f, &base_t, 0);
          fprintf(f, " ");
        }
        fprintf(f, "%s", node->fields[j].name ? node->fields[j].name : "arg");
        if (j < node->fields_count - 1 || node->is_variadic)
          fprintf(f, ", ");
      }
      if (node->is_variadic) {
        fprintf(f, "__arglist");
      }
      fprintf(f, ");\n\n");
    }
  }
  fprintf(f, "    }\n");
  fprintf(f, "}\n");

  fclose(f);
  return CDD_C_SUCCESS;
}

static enum cdd_c_error
emit_csharp_tests(cdd_ffi_ir_t *ir,
                  const cdd_generate_bindings_config_t *config) {
  FILE *f;
  char filepath[1024];
  size_t i;
  extern volatile int g_fail_io_after;
  const char *libname = config->library_name ? config->library_name : "libname";

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\BindingsTests.cs",
            config->output_dir);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/BindingsTests.cs",
               config->output_dir);
  f = fopen(filepath, "w");
#endif

  if (g_fail_io_after == 557) {
    if (f) {
      fclose(f);
      f = NULL;
    }
  }

  if (!f)
    return CDD_C_ERROR_IO;

  fprintf(f, "using System;\n");
  fprintf(f, "using System.Runtime.InteropServices;\n");
  fprintf(f, "using NUnit.Framework;\n\n");
  fprintf(f, "namespace %sBindings.Tests\n{\n", libname);
  fprintf(f, "    [TestFixture]\n");
  fprintf(f, "    public class NativeMethodsTests\n    {\n");

  for (i = 0; i < ir->nodes_count; i++) {
    cdd_ffi_ir_node_t *node = &ir->nodes[i];
    if (node->kind == CDD_FFI_NODE_STRUCT || node->kind == CDD_FFI_NODE_UNION) {
      fprintf(f, "        [Test]\n");
      fprintf(f, "        public void Test%sSize()\n        {\n", node->name);
      fprintf(f, "            int size = Marshal.SizeOf(typeof(%s));\n",
              node->name);
      fprintf(f, "            Assert.Greater(size, 0);\n");
      fprintf(f, "        }\n\n");
    }
  }

  fprintf(f, "    }\n");
  fprintf(f, "}\n");

  fclose(f);
  return CDD_C_SUCCESS;
}

static enum cdd_c_error
emit_csproj(const cdd_generate_bindings_config_t *config) {
  FILE *f;
  char filepath[1024];
  extern volatile int g_fail_io_after;
  const char *libname = config->library_name ? config->library_name : "libname";

#if defined(_MSC_VER)
  sprintf_s(filepath, sizeof(filepath), "%s\\%sBindings.csproj",
            config->output_dir, libname);
  fopen_s(&f, filepath, "w");
#else
  CDD_SNPRINTF(filepath, sizeof(filepath), "%s/%sBindings.csproj",
               config->output_dir, libname);
  f = fopen(filepath, "w");
#endif

  if (g_fail_io_after == 556) {
    if (f) {
      fclose(f);
      f = NULL;
    }
  }

  if (!f)
    return CDD_C_ERROR_IO;

  fprintf(f, "<Project Sdk=\"Microsoft.NET.Sdk\">\n");
  fprintf(f, "  <PropertyGroup>\n");
  fprintf(f, "    <TargetFramework>netstandard2.0</TargetFramework>\n");
  fprintf(f, "    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n");
  fprintf(f, "  </PropertyGroup>\n");
  fprintf(f, "  <ItemGroup Condition=\" '$(Configuration)' == 'Test' \">\n");
  fprintf(f, "    <PackageReference Include=\"nunit\" Version=\"3.13.3\" />\n");
  fprintf(f, "    <PackageReference Include=\"NUnit3TestAdapter\" "
             "Version=\"4.2.1\" />\n");
  fprintf(f, "    <PackageReference Include=\"Microsoft.NET.Test.Sdk\" "
             "Version=\"17.0.0\" />\n");
  fprintf(f, "  </ItemGroup>\n");
  fprintf(f, "</Project>\n");

  fclose(f);
  return CDD_C_SUCCESS;
}

enum cdd_c_error
cdd_ffi_emit_csharp(cdd_ffi_ir_t *ir,
                    const cdd_generate_bindings_config_t *config) {
  int rc;

  if (!ir || !config || !config->output_dir)
    return CDD_C_ERROR_INVALID_ARGUMENT;

  makedir(config->output_dir);

  rc = emit_csharp_bindings(ir, config);
  if (rc != 0)
    return rc;

  rc = emit_csproj(config);
  if (rc != 0)
    return rc;

  if (config->generate_tests) {
    rc = emit_csharp_tests(ir, config);
    if (rc != 0)
      return rc;
  }

  return CDD_C_SUCCESS;
}
