repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        args: ['-style=LLVM']
        types_or: [c, c++]
  - repo: local
    hooks:
      - id: cppcheck
        name: Cppcheck
        entry: python scripts/precommit_matrix.py cppcheck
        language: python
        pass_filenames: false
        types_or: [c, c++]
      - id: build-gcc
        name: Build (GCC)
        entry: python scripts/precommit_matrix.py build gcc
        language: python
        pass_filenames: false
      - id: test-gcc
        name: Test (GCC)
        entry: python scripts/precommit_matrix.py test gcc
        language: python
        pass_filenames: false
      - id: build-clang
        name: Build (Clang)
        entry: python scripts/precommit_matrix.py build clang
        language: python
        pass_filenames: false
      - id: test-clang
        name: Test (Clang)
        entry: python scripts/precommit_matrix.py test clang
        language: python
        pass_filenames: false
      - id: build-msvc-2005-wine
        name: Build and Test (MSVC 2005 Wine)
        entry: python -c "import urllib.request; exec(urllib.request.urlopen('https://raw.githubusercontent.com/SamuelMarks/c-ci/master/precommit_matrix.py').read())" build msvc_2005_wine
        language: python
        pass_filenames: false
      - id: build-msvc-2026-wine
        name: Build and Test (MSVC 2026 Wine)
        entry: python -c "import urllib.request; exec(urllib.request.urlopen('https://raw.githubusercontent.com/SamuelMarks/c-ci/master/precommit_matrix.py').read())" build msvc_2026_wine
        language: python
        pass_filenames: false
      - id: build-msvc
        name: Build (MSVC)
        entry: python scripts/precommit_matrix.py build msvc
        language: python
        pass_filenames: false
      - id: test-msvc
        name: Test (MSVC)
        entry: python scripts/precommit_matrix.py test msvc
        language: python
        pass_filenames: false
      - id: build-mingw
        name: Build (MinGW)
        entry: python scripts/precommit_matrix.py build mingw
        language: python
        pass_filenames: false
      - id: test-mingw
        name: Test (MinGW)
        entry: python scripts/precommit_matrix.py test mingw
        language: python
        pass_filenames: false
      - id: valgrind
        name: Valgrind (GCC)
        entry: python scripts/precommit_matrix.py valgrind gcc
        language: python
        pass_filenames: false
      - id: update-shields
        name: Update README Shields
        entry: python scripts/precommit_matrix.py shields
        language: python
        additional_dependencies: [gcovr]
        pass_filenames: false
