repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: '\.(bat|cmd|ps1)$'
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file", "-i"]
  - repo: local
    hooks:
      - id: build
        name: Build
        entry: python scripts/pre_commit.py build
        language: python
        pass_filenames: false
        always_run: true
      - id: test
        name: Test
        entry: python scripts/pre_commit.py test
        language: python
        pass_filenames: false
        always_run: true
      - id: lint
        name: Lint
        entry: python scripts/pre_commit.py lint
        language: python
        pass_filenames: false
        always_run: true
      - id: update-shields
        name: Update Shields & Validate OpenAPI
        entry: python scripts/pre_commit.py shields
        language: python
        pass_filenames: false
        always_run: true
