/**
 * @file hydrate_router.h
 * @brief Dynamic runtime routing API for C-ORM struct hydration.
 *
 * Implements Phase 3 Fallback logic: matching dynamic query results
 * to specific C structs if available, or gracefully failing over to
 * the generic cdd_c_abstract_struct_t mappings.
 *
 * @author Samuel Marks
 */

#ifndef C_CDD_CLASSES_PARSE_HYDRATE_ROUTER_H
#define C_CDD_CLASSES_PARSE_HYDRATE_ROUTER_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include "c_cdd_export.h"
#include "classes/parse/abstract_struct.h"
#include "classes/emit/c_orm_meta.h"
/* clang-format on */

/**
 * @brief Function pointer definition for a specific struct hydrator.
 */
typedef int (*cdd_c_specific_hydrator_fn)(void *out_struct,
                                          const cdd_c_abstract_struct_t *row);

struct c_orm_meta; /* Forward decl */

/**
 * @brief Mapping entry to associate a dynamic query hash/ID with its specific
 * struct codegen.
 */
typedef struct CddCHydrateRoute {
  unsigned long long query_id_hash;
  const struct c_orm_meta *struct_meta;
  cdd_c_specific_hydrator_fn hydrate_fn;
} cdd_c_hydrate_route_t;

/**
 * @brief Opaque router instance to handle dynamic struct delegation.
 */
typedef struct CddCHydrateRouter {
  cdd_c_hydrate_route_t *routes;
  size_t count;
  size_t capacity;
} cdd_c_hydrate_router_t;

/**
 * @brief Initialize a new hydrate router.
 * @param router The router instance.
 * @return 0 on success.
 */
C_CDD_EXPORT int cdd_c_hydrate_router_init(cdd_c_hydrate_router_t *router);

/**
 * @brief Get the last routing error message for the current thread.
 * @return Null-terminated error message string, or NULL if no error.
 */
C_CDD_EXPORT const char *cdd_c_hydrate_router_get_last_error(void);

/**
 * @brief Set the last routing error message for the current thread.
 * @param msg The error message to set.
 */
C_CDD_EXPORT void cdd_c_hydrate_router_set_last_error(const char *msg);

/**
 * @brief Register a specific generated struct mapping into the router.
 * @param router The router instance.
 * @param query_id_hash A stable hash tracking the exact SQL string layout.
 * @param struct_meta Reflected ORM structural bounds.
 * @param hydrate_fn Pointer to the autogenerated hydration method (e.g.
 * `StructName_hydrate`).
 * @return 0 on success.
 */
C_CDD_EXPORT int
cdd_c_hydrate_router_register(cdd_c_hydrate_router_t *router,
                              unsigned long long query_id_hash,
                              const struct c_orm_meta *struct_meta,
                              cdd_c_specific_hydrator_fn hydrate_fn);

/**
 * @brief Route an incoming abstract dictionary row directly into a specific C
 * struct.
 * @param router The router instance.
 * @param query_id_hash The target query hash to resolve.
 * @param row The dynamic generic database row mapping payload.
 * @param out_struct Pointer to allocated target struct instance.
 * @return 0 on successful exact route and hydration. -1 if fallback is
 * necessary or mapping failed.
 */
C_CDD_EXPORT int cdd_c_hydrate_router_dispatch(
    const cdd_c_hydrate_router_t *router, unsigned long long query_id_hash,
    const cdd_c_abstract_struct_t *row, void *out_struct);

/**
 * @brief Free internal router resources.
 * @param router The router instance.
 * @return 0 on success.
 */
C_CDD_EXPORT int cdd_c_hydrate_router_free(cdd_c_hydrate_router_t *router);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_CLASSES_PARSE_HYDRATE_ROUTER_H */
