/**
 * @file migration.h
 * @brief Parser and representation for SQL migration files.
 *
 * @author Samuel Marks
 */

#ifndef C_CDD_MIGRATION_H
#define C_CDD_MIGRATION_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include "c_cdd_export.h"
#include <stddef.h>
/* clang-format on */

/**
 * @brief Representation of a parsed SQL migration file.
 */
struct MigrationStatements {
  char *up_statement;   /**< The UP part of the migration */
  char *down_statement; /**< The DOWN part of the migration */
};

/**
 * @brief Initialize a migration statements structure.
 * @param[out] out The structure to zero.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    void
    migration_statements_init(struct MigrationStatements *out);

/**
 * @brief Free resources in a migration statements structure.
 * @param[in] out The structure to clean.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    void
    migration_statements_free(struct MigrationStatements *out);

/**
 * @brief Parse a SQL migration file into UP and DOWN statements.
 *
 * Reads a .sql file and splits its contents based on -- UP and -- DOWN markers.
 * If no markers are present, the whole file might be considered as UP depending
 * on implementation.
 *
 * @param[in] filepath The path to the .sql migration file.
 * @param[out] out The populated migration statements structure.
 * @return 0 on success, ENOMEM on allocation failure, or a standard I/O error
 * code.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    parse_migration_file(const char *filepath, struct MigrationStatements *out);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_MIGRATION_H */
