/**
 * @file sql.h
 * @brief Parses SQL DDL into an AST.
 */

#ifndef C_CDD_SQL_PARSER_H
#define C_CDD_SQL_PARSER_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include "c_cdd_export.h"
#include <stddef.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
#pragma GCC diagnostic ignored "-Wc++-compat"
#pragma GCC diagnostic ignored "-Wattributes"
#endif
#include <c_str_span.h>
/* clang-format on */
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif

/*
 * Phase 1: AST Node Structs
 */

/**
 * @brief Represents SQL Data Types.
 */
enum SqlDataType {
  SQL_TYPE_UNKNOWN,
  SQL_TYPE_INT,
  SQL_TYPE_BIGINT,
  SQL_TYPE_VARCHAR,
  SQL_TYPE_TEXT,
  SQL_TYPE_CHAR,
  SQL_TYPE_FLOAT,
  SQL_TYPE_DOUBLE,
  SQL_TYPE_DECIMAL,
  SQL_TYPE_BOOLEAN,
  SQL_TYPE_DATE,
  SQL_TYPE_TIMESTAMP
};

/**
 * @brief Represents a SQL Column Constraint Type.
 */
enum SqlConstraintType {
  SQL_CONSTRAINT_NONE,
  SQL_CONSTRAINT_PRIMARY_KEY,
  SQL_CONSTRAINT_FOREIGN_KEY,
  SQL_CONSTRAINT_UNIQUE,
  SQL_CONSTRAINT_NOT_NULL,
  SQL_CONSTRAINT_DEFAULT
};

/**
 * @brief Represents a single SQL Constraint.
 */
struct sql_constraint_t {
  enum SqlConstraintType type;
  char *reference_table;  /**< For FOREIGN KEY */
  char *reference_column; /**< For FOREIGN KEY */
  char *default_value;    /**< For DEFAULT */
};

/**
 * @brief Represents a single SQL Column definition.
 */
struct sql_column_t {
  char *name;
  enum SqlDataType type;
  int length; /**< For VARCHAR(n), etc., -1 if not specified */
  struct sql_constraint_t *constraints;
  size_t n_constraints;
};

/**
 * @brief Represents a SQL Table definition.
 */
struct sql_table_t {
  char *name;
  struct sql_column_t *columns;
  size_t n_columns;
  struct sql_constraint_t *table_constraints; /**< Table-level constraints */
  size_t n_table_constraints;
};

/*
 * Phase 1: Lexer & Tokenizer
 */

/**
 * @brief Classification of SQL lexical elements.
 */
enum SqlTokenKind {
  SQL_TOKEN_EOF,
  SQL_TOKEN_WHITESPACE,
  SQL_TOKEN_IDENTIFIER,
  SQL_TOKEN_KEYWORD,
  SQL_TOKEN_NUMBER,
  SQL_TOKEN_STRING,
  SQL_TOKEN_LPAREN,
  SQL_TOKEN_RPAREN,
  SQL_TOKEN_COMMA,
  SQL_TOKEN_SEMICOLON,
  SQL_TOKEN_UNKNOWN
};

/**
 * @brief A single SQL lexical unit.
 */
struct sql_token_t {
  enum SqlTokenKind kind;
  const char *start;
  size_t length;
};

/**
 * @brief A list of SQL tokens.
 */
struct sql_token_list_t {
  struct sql_token_t *tokens;
  size_t size;
  size_t capacity;
};

/**
 * @brief Error information returned by the SQL parser.
 */
struct sql_parse_error_t {
  const char *message;
  const struct sql_token_t *token;
};

/**
 * @brief Lex a SQL string into a token list.
 *
 * @param source The SQL source text.
 * @param out_list Pointer to pointer of list to allocate and populate.
 * @return 0 on success, non-zero on error.
 */
C_CDD_EXPORT int sql_lex(az_span source, struct sql_token_list_t **out_list);

/**
 * @brief Parse a SQL CREATE TABLE statement.
 *
 * @param list The token list generated by sql_lex.
 * @param out_table Pointer to pointer to allocate and populate with AST.
 * @param out_error Pointer to populate with error info on failure.
 * @return 0 on success, non-zero on error.
 */
C_CDD_EXPORT int sql_parse_table(const struct sql_token_list_t *list,
                                 struct sql_table_t **out_table,
                                 struct sql_parse_error_t *out_error);

/**
 * @brief Free a SQL token list.
 *
 * @param list The list to free.
 * @return 0 on success.
 */
C_CDD_EXPORT int sql_token_list_free(struct sql_token_list_t *list);

/**
 * @brief Free a SQL table AST node.
 *
 * @param table The table to free.
 * @return 0 on success.
 */
C_CDD_EXPORT int sql_table_free(struct sql_table_t *table);

/**
 * @brief Parse full SQL DDL file returning all tables.
 *
 * @param sql_data SQL source text
 * @param out_tables Pointer to receive array of tables
 * @param out_n_tables Pointer to receive count
 * @return 0 on success
 */
C_CDD_EXPORT int parse_sql_ddl(const char *sql_data,
                               struct sql_table_t **out_tables,
                               size_t *out_n_tables);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_SQL_PARSER_H */