/**
 * @file database.h
 * @brief Intermediate Representation (IR) mapping for relational databases.
 *
 * Defines the AST structures needed for parsing C structs into Database schemas.
 */

#ifndef C_CDD_DATABASE_H
#define C_CDD_DATABASE_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stddef.h>

#include "c_cdd_export.h"

/**
 * @brief Represents the data type of a column.
 */
enum DatabaseColumnType {
  DB_COL_TYPE_UNKNOWN,
  DB_COL_TYPE_INTEGER,
  DB_COL_TYPE_VARCHAR,
  DB_COL_TYPE_TEXT,
  DB_COL_TYPE_REAL,
  DB_COL_TYPE_BLOB,
  DB_COL_TYPE_BOOLEAN,
  DB_COL_TYPE_DATE,
  DB_COL_TYPE_DATETIME
};

/**
 * @brief Represents a single column in a database table.
 */
struct DatabaseColumn {
  char *name;                     /**< Name of the column. */
  enum DatabaseColumnType type;   /**< Data type of the column. */
  int is_primary_key;             /**< 1 if primary key, 0 otherwise. */
  int is_nullable;                /**< 1 if nullable, 0 otherwise. */
  int is_unique;                  /**< 1 if unique, 0 otherwise. */
  char *default_value;            /**< Default value as string, or NULL. */
  char *foreign_key_table;        /**< Table this column references, or NULL. */
  char *foreign_key_column;       /**< Column this column references, or NULL. */
};

/**
 * @brief Represents a database table.
 */
struct DatabaseTable {
  char *name;                     /**< Name of the table. */
  struct DatabaseColumn *columns; /**< Array of columns. */
  size_t n_columns;               /**< Number of columns. */
};

/**
 * @brief Represents a complete database schema.
 */
struct DatabaseSchema {
  char *name;                     /**< Name of the schema/database. */
  struct DatabaseTable *tables;   /**< Array of tables. */
  size_t n_tables;                /**< Number of tables. */
};

/**
 * @brief Initialize a DatabaseSchema.
 */
C_CDD_EXPORT /**
 * @brief Autogenerated docstring
 */
void db_schema_init(struct DatabaseSchema *schema);

/**
 * @brief Free resources associated with a DatabaseSchema.
 */
C_CDD_EXPORT /**
 * @brief Autogenerated docstring
 */
void db_schema_free(struct DatabaseSchema *schema);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_DATABASE_H */
