/* clang-format off */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "classes/emit/form.h"
#include "classes/emit/struct.h"
#include "win_compat_sym.h"
/* clang-format on */

int write_struct_to_form_urlencoded_func(FILE *fp, const char *struct_name,
                                         const struct StructFields *sf) {
  size_t i;
  if (!fp || !struct_name || !sf)
    return EINVAL;

  fprintf(fp, "/**\n * @brief Percent-encode a string for "
              "application/x-www-form-urlencoded.\n */\n");
  fprintf(fp, "static int %s_url_encode_form(const char *str, char **out) {\n",
          struct_name);
  fprintf(fp, "  size_t len = 0, idx = 0, out_idx = 0;\n");
  fprintf(fp, "  char *res;\n");
  fprintf(fp, "  if (!str || !out) return 1;\n");
  fprintf(fp, "  for (idx = 0; str[idx]; ++idx) {\n");
  fprintf(fp, "    unsigned char c = (unsigned char)str[idx];\n");
  fprintf(fp, "    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||\n");
  fprintf(fp, "        (c >= '0' && c <= '9') || c == '-' || c == '.' || c == "
              "'_' || c == '~') {\n");
  fprintf(fp, "      len++;\n");
  fprintf(fp, "    } else if (c == ' ') {\n");
  fprintf(fp, "      len++;\n");
  fprintf(fp, "    } else {\n");
  fprintf(fp, "      len += 3;\n");
  fprintf(fp, "    }\n");
  fprintf(fp, "  }\n");
  fprintf(fp, "  res = (char *)malloc(len + 1);\n");
  fprintf(fp, "  if (!res) return 1;\n");
  fprintf(fp, "  for (idx = 0; str[idx]; ++idx) {\n");
  fprintf(fp, "    unsigned char c = (unsigned char)str[idx];\n");
  fprintf(fp, "    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||\n");
  fprintf(fp, "        (c >= '0' && c <= '9') || c == '-' || c == '.' || c == "
              "'_' || c == '~') {\n");
  fprintf(fp, "      res[out_idx++] = (char)c;\n");
  fprintf(fp, "    } else if (c == ' ') {\n");
  fprintf(fp, "      res[out_idx++] = '+';\n");
  fprintf(fp, "    } else {\n");
  fprintf(fp, "#if defined(_MSC_VER)\\n");
  fprintf(fp, "      sprintf_s(res + out_idx, 3, \"%%02X\", c);\\n");
  fprintf(fp, "#else\\n");
  fprintf(fp, "      sprintf(res + out_idx, \"%%02X\", c);\\n");
  fprintf(fp, "#endif\\n");
  fprintf(fp, "      res[out_idx - 1] = '%%';\n");
  fprintf(fp, "      out_idx += 3;\n");
  fprintf(fp, "    }\n");
  fprintf(fp, "  }\n");
  fprintf(fp, "  res[out_idx] = '\\0';\n");
  fprintf(fp, "  *out = res;\n");
  fprintf(fp, "  return 0;\n");
  fprintf(fp, "}\n\n");

  fprintf(fp, "/**\n * @brief Autogenerated Struct-to-Form automatic "
              "generation.\n */\n");
  fprintf(fp, "int %s_to_form_urlencoded(const struct %s *obj, char **out) {\n",
          struct_name, struct_name);
  fprintf(fp, "  char *res = NULL;\n");
  fprintf(fp, "  size_t capacity = 128, length = 0;\n");
  fprintf(fp, "  int is_first = 1;\n");
  fprintf(fp, "  if (!obj || !out) return 1;\n");
  fprintf(fp, "  res = (char *)malloc(capacity);\n");
  fprintf(fp, "  if (!res) return 1;\n");
  fprintf(fp, "  res[0] = '\\0';\n\n");

  fprintf(fp, "  /* Helper logic to append strings with dynamic resizing */\n");
  for (i = 0; i < sf->size; ++i) {
    const struct StructField *f = &sf->fields[i];
    if (strcmp(f->type, "string") == 0) {
      fprintf(fp, "  if (obj->%s) {\n", f->name);
      fprintf(fp, "    char *encoded = NULL;\n");
      fprintf(fp, "    if (%s_url_encode_form(obj->%s, &encoded) == 0) {\n",
              struct_name, f->name);
      fprintf(fp, "      size_t slen = strlen(encoded) + %lu + 2;\n",
              (unsigned long)strlen(f->name));
      fprintf(fp, "      if (length + slen + 1 > capacity) {\n");
      fprintf(fp, "        char *tmp;\n");
      fprintf(fp, "        capacity = (length + slen + 1) * 2;\n");
      fprintf(fp, "        tmp = (char *)realloc(res, capacity);\n");
      fprintf(fp,
              "        if (!tmp) { free(res); free(encoded); return 1; }\n");
      fprintf(fp, "        res = tmp;\n");
      fprintf(fp, "      }\n");
      fprintf(fp, "      if (!is_first) {\\n");
      fprintf(fp, "#if defined(_MSC_VER)\\n");
      fprintf(fp,
              "        strcpy_s(res + length, capacity - length, \"&\");\\n");
      fprintf(fp, "#else\\n");
      fprintf(fp, "        strcpy(res + length, \"&\");\\n");
      fprintf(fp, "#endif\\n");
      fprintf(fp, "        length++;\\n      }\\n");
      fprintf(fp, "      strcpy(res + length, \"%s=\"); length += %lu;\n",
              f->name, (unsigned long)strlen(f->name) + 1);
      fprintf(
          fp,
          "      strcpy(res + length, encoded); length += strlen(encoded);\n");
      fprintf(fp, "      free(encoded);\n");
      fprintf(fp, "      is_first = 0;\n");
      fprintf(fp, "    } else {\n");
      fprintf(fp, "      free(res);\n");
      fprintf(fp, "      return 1;\n");
      fprintf(fp, "    }\n");
      fprintf(fp, "  }\n");
    } else if (strcmp(f->type, "integer") == 0) {
      fprintf(fp, "  {\n    char buf[32];\n");
      fprintf(fp, "    size_t slen;\n");
      fprintf(fp, "#if defined(_MSC_VER)\\n");
      fprintf(fp, "    sprintf_s(buf, sizeof(buf), \"%%d\", obj->%s);\\n",
              f->name);
      fprintf(fp, "#else\\n");
      fprintf(fp, "    sprintf(buf, \"%%d\", obj->%s);\\n", f->name);
      fprintf(fp, "#endif\\n");
      fprintf(fp, "    slen = strlen(buf) + %lu + 2;\n",
              (unsigned long)strlen(f->name));
      fprintf(fp, "    if (length + slen + 1 > capacity) {\n");
      fprintf(fp, "      char *tmp;\n");
      fprintf(fp, "      capacity = (length + slen + 1) * 2;\n");
      fprintf(fp, "      tmp = (char *)realloc(res, capacity);\n");
      fprintf(fp, "      if (!tmp) { free(res); return 1; }\n");
      fprintf(fp, "      res = tmp;\n");
      fprintf(fp, "    }\n");
      fprintf(fp, "      if (!is_first) {\\n");
      fprintf(fp, "#if defined(_MSC_VER)\\n");
      fprintf(fp,
              "        strcpy_s(res + length, capacity - length, \"&\");\\n");
      fprintf(fp, "#else\\n");
      fprintf(fp, "        strcpy(res + length, \"&\");\\n");
      fprintf(fp, "#endif\\n");
      fprintf(fp, "        length++;\\n      }\\n");
      fprintf(fp, "    strcpy(res + length, \"%s=\"); length += %lu;\n",
              f->name, (unsigned long)strlen(f->name) + 1);
      fprintf(fp, "    strcpy(res + length, buf); length += strlen(buf);\n");
      fprintf(fp, "    is_first = 0;\n  }\n");
    } else if (strcmp(f->type, "boolean") == 0) {
      fprintf(fp,
              "  {\n    const char *val = obj->%s ? \"true\" : \"false\";\n",
              f->name);
      fprintf(fp, "    size_t slen = strlen(val) + %lu + 2;\n",
              (unsigned long)strlen(f->name));
      fprintf(fp, "    if (length + slen + 1 > capacity) {\n");
      fprintf(fp, "      char *tmp;\n");
      fprintf(fp, "      capacity = (length + slen + 1) * 2;\n");
      fprintf(fp, "      tmp = (char *)realloc(res, capacity);\n");
      fprintf(fp, "      if (!tmp) { free(res); return 1; }\n");
      fprintf(fp, "      res = tmp;\n");
      fprintf(fp, "    }\n");
      fprintf(fp, "      if (!is_first) {\\n");
      fprintf(fp, "#if defined(_MSC_VER)\\n");
      fprintf(fp,
              "        strcpy_s(res + length, capacity - length, \"&\");\\n");
      fprintf(fp, "#else\\n");
      fprintf(fp, "        strcpy(res + length, \"&\");\\n");
      fprintf(fp, "#endif\\n");
      fprintf(fp, "        length++;\\n      }\\n");
      fprintf(fp, "    strcpy(res + length, \"%s=\"); length += %lu;\n",
              f->name, (unsigned long)strlen(f->name) + 1);
      fprintf(fp, "    strcpy(res + length, val); length += strlen(val);\n");
      fprintf(fp, "    is_first = 0;\n  }\n");
    }
  }

  fprintf(fp, "  *out = res;\n");
  fprintf(fp, "  return 0;\n");
  fprintf(fp, "}\n");
  return 0;
}