/* clang-format off */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "classes/emit/json.h"
#include "classes/emit/struct.h"
/* clang-format on */

int write_struct_from_json_standalone_func(FILE *fp, const char *struct_name,
                                           const struct StructFields *sf) {
  size_t i;

  if (!fp || !struct_name || !sf)
    return EINVAL;

  fprintf(fp,
          "/**\n"
          " * @brief Autogenerated zero-allocation JSON parser for %s.\n"
          " * @param[in,out] json Mutable JSON string to parse.\n"
          " * @param[out] out Pointer to store the parsed struct.\n"
          " * @return 0 on success, non-zero on error.\n"
          " */\n",
          struct_name);
  fprintf(fp, "int %s_parse_json(char *json, struct %s **const out) {\n",
          struct_name, struct_name);
  fprintf(fp, "  struct %s *ret;\n", struct_name);
  fprintf(fp, "  char *p = json;\n");
  fprintf(fp, "  char *key;\n");
  fprintf(fp, "  char *val;\n\n");

  /* Missing/Required handling variables */
  for (i = 0; i < sf->size; ++i) {
    if (sf->fields[i].required) {
      fprintf(fp, "  int has_%s = 0;\n", sf->fields[i].name);
    }
  }

  fprintf(fp, "  if (!json || !out) return 1;\n");
  fprintf(fp, "  ret = (struct %s *)calloc(1, sizeof(struct %s));\n",
          struct_name, struct_name);
  fprintf(fp, "  if (!ret) return 1;\n\n");

  fprintf(fp, "  while (*p) {\n");
  /* Find next key */
  fprintf(fp, "    while (*p && *p != '\"') p++;\n");
  fprintf(fp, "    if (!*p) break;\n");
  fprintf(fp, "    p++;\n");
  fprintf(fp, "    key = p;\n");
  fprintf(fp, "    while (*p && *p != '\"') p++;\n");
  fprintf(fp, "    if (!*p) break;\n");
  fprintf(fp, "    *p++ = '\\0';\n");

  /* Find next value */
  fprintf(fp, "    while (*p && *p != ':') p++;\n");
  fprintf(fp, "    if (!*p) break;\n");
  fprintf(fp, "    p++;\n");
  fprintf(fp, "    while (*p && (*p == ' ' || *p == '\\t' || *p == '\\n' || *p "
              "== '\\r')) p++;\n\n");

  /* Parse String value */
  fprintf(fp, "    if (*p == '\"') {\n");
  fprintf(fp, "      p++;\n");
  fprintf(fp, "      val = p;\n");
  fprintf(fp, "      while (*p && *p != '\"') {\n");
  fprintf(fp, "        if (*p == '\\\\' && *(p+1)) p += 2;\n");
  fprintf(fp, "        else p++;\n");
  fprintf(fp, "      }\n");
  fprintf(fp, "      if (*p) *p++ = '\\0';\n\n");

  /* Assign strings */
  for (i = 0; i < sf->size; ++i) {
    const struct StructField *f = &sf->fields[i];
    if (strcmp(f->type, "string") == 0) {
      fprintf(fp, "      %s (strcmp(key, \"%s\") == 0) {\n",
              (i == 0) ? "if" : "else if", f->name);
      if (f->has_max_len) {
        fprintf(fp, "        if (strlen(val) > %lu) goto err;\n",
                (unsigned long)f->max_len);
      }
      if (f->has_min_len) {
        fprintf(fp, "        if (strlen(val) < %lu) goto err;\n",
                (unsigned long)f->min_len);
      }
      fprintf(fp, "        ret->%s = val;\n", f->name);
      if (f->required) {
        fprintf(fp, "        has_%s = 1;\n", f->name);
      }
      fprintf(fp, "      }\n");
    }
  }

  /* Parse Number / Boolean / Null / etc */
  fprintf(fp, "    } else {\n");
  fprintf(fp, "      val = p;\n");
  fprintf(fp, "      while (*p && *p != ',' && *p != '}' && *p != ' ' && *p != "
              "'\\n' && *p != '\\r') p++;\n");
  fprintf(fp, "      if (*p) *p++ = '\\0';\n\n");

  /* Assign numbers */
  for (i = 0; i < sf->size; ++i) {
    const struct StructField *f = &sf->fields[i];
    if (strcmp(f->type, "integer") == 0 || strcmp(f->type, "number") == 0) {
      fprintf(fp, "      %s (strcmp(key, \"%s\") == 0) {\n",
              (i == 0) ? "if" : "else if", f->name);
      if (strcmp(f->type, "integer") == 0) {
        fprintf(fp, "        ret->%s = atoi(val);\n", f->name);
      } else {
        fprintf(fp, "        ret->%s = atof(val);\n", f->name);
      }
      if (f->required) {
        fprintf(fp, "        has_%s = 1;\n", f->name);
      }
      fprintf(fp, "      }\n");
    } else if (strcmp(f->type, "boolean") == 0) {
      fprintf(fp, "      %s (strcmp(key, \"%s\") == 0) {\n",
              (i == 0) ? "if" : "else if", f->name);
      fprintf(fp, "        ret->%s = (strcmp(val, \"true\") == 0) ? 1 : 0;\n",
              f->name);
      if (f->required) {
        fprintf(fp, "        has_%s = 1;\n", f->name);
      }
      fprintf(fp, "      }\n");
    }
  }

  fprintf(fp, "    }\n");
  fprintf(fp, "  }\n\n");

  /* Check required fields */
  for (i = 0; i < sf->size; ++i) {
    if (sf->fields[i].required) {
      fprintf(fp, "  if (!has_%s) goto err;\n", sf->fields[i].name);
    }
  }

  fprintf(fp, "  *out = ret;\n");
  fprintf(fp, "  return 0;\n");

  fprintf(fp, "\nerr:\n");
  fprintf(fp, "  free(ret);\n");
  fprintf(fp, "  return 1;\n");
  fprintf(fp, "}\n");
  return 0;
}
