/**
 * @file cli_gen.h
 * @brief Generate a CLI wrapper for the OpenAPI SDK.
 */

#ifndef C_CDD_OPENAPI_CLI_GEN_H
#define C_CDD_OPENAPI_CLI_GEN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "c_cdd_export.h"
#include "openapi/parse/openapi.h"
#include "routes/emit/client_gen.h"

/**
 * @brief Generate CLI C source file.
 * @param spec OpenAPI specification.
 * @param config Client configuration.
 * @return 0 on success, non-zero on error.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    openapi_cli_generate(const struct OpenAPI_Spec *spec,
                         const struct OpenApiClientConfig *config);

#ifdef __cplusplus
}
#endif

#endif
