/**
 * @file client_gen_url_utils_c2.c
 * @brief url_utils.c (part 2) emission for OpenAPI client generator.
 */

/* clang-format off */
#include "c_cdd/safe_crt_msvc.h"

#include "routes/emit/client_gen_internal.h"
#include "c_cdd/log.h"
#include "c_cdd/safe_crt.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* clang-format on */

/**
 * @brief Emit url_utils.c (part 2) for installable package.
 */
cdd_c_error_t client_gen_emit_url_utils_c2(FILE *uc) {
  if (uc) {
    fputs("/**\n"
          " * @brief Executes the url query free operation.\n"
          " */\n"
          "void url_query_free(struct UrlQueryParams *qp) {\n"
          "  size_t i;\n"
          "  if (!qp)\n"
          "    return;\n"
          "  if (qp->params) {\n"
          "    for (i = 0; i < qp->count; ++i) {\n",
          uc);
    fputs("      if (qp->params[i].key)\n"
          "        free(qp->params[i].key);\n"
          "      if (qp->params[i].value)\n"
          "        free(qp->params[i].value);\n"
          "    }\n"
          "    free(qp->params);\n"
          "    qp->params = NULL;\n"
          "  }\n"
          "  qp->count = 0;\n"
          "  qp->capacity = 0;\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Executes the url query add operation.\n"
          " */\n"
          "cdd_c_error_t url_query_add(struct UrlQueryParams *qp, const ",
          uc);
    fputs("char *key,\n"
          "                  const char *value) {\n"
          "  char *_ast_strdup_0 = NULL;\n"
          "  char *_ast_strdup_1 = NULL;\n"
          "  if (!qp || !key || !value)\n"
          "    return CDD_C_ERROR_INVALID_ARGUMENT;\n"
          "\n"
          "  if (qp->count >= qp->capacity) {\n"
          "    size_t new_cap = (qp->capacity == 0) ? 4 : qp->capacity * 2;\n"
          "    struct UrlQueryParam *new_arr = (struct UrlQueryParam "
          "*)realloc(\n",
          uc);
    fputs("        qp->params, new_cap * sizeof(struct UrlQueryParam));\n"
          "    if (!new_arr) {\n"
          "      C_CDD_LOG_DEBUG(\"ENOMEM: OOM\\n\");\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    qp->params = new_arr;\n"
          "    qp->capacity = new_cap;\n"
          "  }\n"
          "\n"
          "  qp->params[qp->count].key =\n"
          "      (c_cdd_strdup(key, &_ast_strdup_0), _ast_strdup_0);\n"
          "  if (!qp->params[qp->count].key)\n",
          uc);
    fputs("    return CDD_C_ERROR_MEMORY;\n"
          "\n"
          "  qp->params[qp->count].value =\n"
          "      (c_cdd_strdup(value, &_ast_strdup_1), _ast_strdup_1);\n"
          "  if (!qp->params[qp->count].value) {\n"
          "    free(qp->params[qp->count].key);\n"
          "    return CDD_C_ERROR_MEMORY;\n"
          "  }\n"
          "  qp->params[qp->count].value_is_encoded = 0;\n"
          "\n"
          "  qp->count++;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "/**\n",
          uc);
    fputs(" * @brief Executes the url query add encoded operation.\n"
          " */\n"
          "cdd_c_error_t url_query_add_encoded(struct UrlQueryParams *qp, "
          "const char "
          "*key,\n"
          "                          const char *value) {\n"
          "  char *_ast_strdup_2 = NULL;\n"
          "  char *_ast_strdup_3 = NULL;\n"
          "  if (!qp || !key || !value)\n"
          "    return CDD_C_ERROR_INVALID_ARGUMENT;\n"
          "\n"
          "  if (qp->count >= qp->capacity) {\n",
          uc);
    fputs("    size_t new_cap = (qp->capacity == 0) ? 4 : qp->capacity * 2;\n"
          "    struct UrlQueryParam *new_arr = (struct UrlQueryParam "
          "*)realloc(\n"
          "        qp->params, new_cap * sizeof(struct UrlQueryParam));\n"
          "    if (!new_arr) {\n"
          "      C_CDD_LOG_DEBUG(\"ENOMEM: OOM\\n\");\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    qp->params = new_arr;\n"
          "    qp->capacity = new_cap;\n"
          "  }\n"
          "\n",
          uc);
    fputs("  qp->params[qp->count].key =\n"
          "      (c_cdd_strdup(key, &_ast_strdup_2), _ast_strdup_2);\n"
          "  if (!qp->params[qp->count].key)\n"
          "    return CDD_C_ERROR_MEMORY;\n"
          "\n"
          "  qp->params[qp->count].value =\n"
          "      (c_cdd_strdup(value, &_ast_strdup_3), _ast_strdup_3);\n"
          "  if (!qp->params[qp->count].value) {\n"
          "    free(qp->params[qp->count].key);\n"
          "    return CDD_C_ERROR_MEMORY;\n"
          "  }\n",
          uc);
    fputs("  qp->params[qp->count].value_is_encoded = 1;\n"
          "\n"
          "  qp->count++;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Executes the url query build operation.\n"
          " */\n"
          "cdd_c_error_t url_query_build(const struct UrlQueryParams *qp, "
          "char "
          "**out_str) {\n"
          "  char *_ast_url_encode_10 = NULL;\n"
          "  char *_ast_url_encode_11 = NULL;\n"
          "  char *_ast_url_encode_12 = NULL;\n",
          uc);
    fputs("  char *_ast_url_encode_13 = NULL;\n"
          "  char *_ast_strdup_4 = NULL;\n"
          "  char *_ast_strdup_5 = NULL;\n"
          "  char *_ast_strdup_6 = NULL;\n"
          "  size_t i;\n"
          "  size_t total_len = 0;\n"
          "  char *buf = NULL;\n"
          "  char *ptr = NULL;\n"
          "\n"
          "  if (!qp || !out_str)\n"
          "    return CDD_C_ERROR_INVALID_ARGUMENT;\n"
          "\n"
          "  if (qp->count == 0) {\n"
          "    *out_str = (c_cdd_strdup(\"\", &_ast_strdup_4), ",
          uc);
    fputs("_ast_strdup_4);\n"
          "    return *out_str ? 0 : ENOMEM;\n"
          "  }\n"
          "\n"
          "  /* 1. Calculate Total Length */\n"
          "  /* Format: ?key=encoded_val&key2=encoded_val2 */\n"
          "  /* Overhead: '?' (1) + ('=' + '&') * count */\n"
          "  /* Actually separators are N-1 '&', 1 '?', N '='. So roughly N + "
          "N + 1. */\n"
          "\n"
          "  total_len = 1; /* '?' */\n"
          "\n"
          "  for (i = 0; i < qp->count; ++i) {\n",
          uc);
    fputs("    char *e_key = (url_encode(qp->params[i].key, "
          "&_ast_url_encode_10),\n"
          "                   _ast_url_encode_10);\n"
          "    char *e_val = NULL;\n"
          "    const char *raw_val = qp->params[i].value;\n"
          "\n"
          "    if (qp->params[i].value_is_encoded) {\n"
          "      e_val =\n"
          "          (c_cdd_strdup(raw_val ? raw_val : \"\", &_ast_strdup_5), "
          "_ast_strdup_5);\n"
          "    } else {\n",
          uc);
    fputs("      e_val = (url_encode(raw_val, &_ast_url_encode_11), "
          "_ast_url_encode_11);\n"
          "    }\n"
          "\n"
          "    if (!e_key || !e_val) {\n"
          "      if (e_key)\n"
          "        free(e_key);\n"
          "      if (e_val)\n"
          "        free(e_val);\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "\n"
          "    total_len += strlen(e_key) + 1; /* key= */\n"
          "    total_len += strlen(e_val);\n"
          "    if (i < qp->count - 1)\n",
          uc);
    fputs("      total_len += 1; /* & */\n"
          "\n"
          "    free(e_key);\n"
          "    free(e_val);\n"
          "  }\n"
          "\n"
          "  /* 2. Allocate */\n"
          "  buf = (char *)(size_t)malloc(total_len + 1);\n"
          "  if (!buf) {\n"
          "    C_CDD_LOG_DEBUG(\"ENOMEM: OOM\\n\");\n"
          "    return CDD_C_ERROR_MEMORY;\n"
          "  }\n"
          "\n"
          "  /* 3. Build */\n"
          "  ptr = buf;\n"
          "  *ptr++ = '?';\n"
          "\n"
          "  for (i = 0; i < qp->count; ++i) {\n",
          uc);
    fputs("    char *e_key = (url_encode(qp->params[i].key, "
          "&_ast_url_encode_12),\n"
          "                   _ast_url_encode_12);\n"
          "    size_t kl, vl;\n"
          "    char *e_val = NULL;\n"
          "    const char *raw_val = qp->params[i].value;\n"
          "\n"
          "    if (qp->params[i].value_is_encoded) {\n"
          "      e_val =\n"
          "          (c_cdd_strdup(raw_val ? raw_val : \"\", &_ast_strdup_6), "
          "_ast_strdup_6);\n"
          "    } else {\n",
          uc);
    fputs("      e_val = (url_encode(raw_val, &_ast_url_encode_13), "
          "_ast_url_encode_13);\n"
          "    }\n"
          "\n"
          "    /* e_key/e_val guaranteed non-null here as checks passed in "
          "pass 1 */\n"
          "    /* Copy Key */\n"
          "    kl = strlen(e_key);\n"
          "    memcpy(ptr, e_key, kl);\n"
          "    ptr += kl;\n"
          "\n"
          "    /* Copy Eq */\n"
          "    *ptr++ = '=';\n"
          "\n"
          "    /* Copy Value */\n"
          "    {\n"
          "      vl = strlen(e_val);\n",
          uc);
    fputs("      memcpy(ptr, e_val, vl);\n"
          "      ptr += vl;\n"
          "    }\n"
          "\n"
          "    /* Copy Sep */\n"
          "    if (i < qp->count - 1) {\n"
          "      *ptr++ = '&';\n"
          "    }\n"
          "\n"
          "    free(e_key);\n"
          "    free(e_val);\n"
          "  }\n"
          "  *ptr = '\\0';\n"
          "\n"
          "  *out_str = buf;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Executes the url query build form operation.\n"
          " */\n",
          uc);
    fputs("cdd_c_error_t url_query_build_form(const struct UrlQueryParams "
          "*qp, char "
          "**out_str) {\n"
          "  char *_ast_url_encode_form_14 = NULL;\n"
          "  char *_ast_url_encode_form_15 = NULL;\n"
          "  char *_ast_url_encode_form_16 = NULL;\n"
          "  char *_ast_url_encode_form_17 = NULL;\n"
          "  char *_ast_strdup_7 = NULL;\n"
          "  char *_ast_strdup_8 = NULL;\n"
          "  size_t i;\n"
          "  size_t total_len = 0;\n"
          "  char *buf;\n",
          uc);
    fputs("  char *ptr;\n"
          "\n"
          "  if (!qp || !out_str)\n"
          "    return CDD_C_ERROR_INVALID_ARGUMENT;\n"
          "\n"
          "  if (qp->count == 0) {\n"
          "    *out_str = (char *)(size_t)calloc(1, 1);\n"
          "    if (!*out_str)\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  for (i = 0; i < qp->count; ++i) {\n"
          "    char *e_key = (url_encode_form(qp->params[i].key, "
          "&_ast_url_encode_form_14),\n",
          uc);
    fputs("                   _ast_url_encode_form_14);\n"
          "    char *e_val;\n"
          "    size_t kl, vl;\n"
          "    if (!e_key) {\n"
          "      C_CDD_LOG_DEBUG(\"ENOMEM: OOM\\n\");\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    if (qp->params[i].value_is_encoded) {\n"
          "      e_val =\n"
          "          (c_cdd_strdup(qp->params[i].value, &_ast_strdup_7), "
          "_ast_strdup_7);\n"
          "    } else {\n",
          uc);
    fputs("      e_val = (url_encode_form(qp->params[i].value, "
          "&_ast_url_encode_form_15),\n"
          "               _ast_url_encode_form_15);\n"
          "    }\n"
          "    if (!e_val) {\n"
          "      free(e_key);\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    kl = strlen(e_key);\n"
          "    vl = strlen(e_val);\n"
          "    total_len += kl + 1 + vl;\n"
          "    if (i + 1 < qp->count)\n"
          "      total_len += 1;\n"
          "    free(e_key);\n",
          uc);
    fputs("    free(e_val);\n"
          "  }\n"
          "\n"
          "  buf = (char *)(size_t)malloc(total_len + 1);\n"
          "  if (!buf) {\n"
          "    C_CDD_LOG_DEBUG(\"ENOMEM: OOM\\n\");\n"
          "    return CDD_C_ERROR_MEMORY;\n"
          "  }\n"
          "  ptr = buf;\n"
          "\n"
          "  for (i = 0; i < qp->count; ++i) {\n"
          "    char *e_key = (url_encode_form(qp->params[i].key, "
          "&_ast_url_encode_form_16),\n"
          "                   _ast_url_encode_form_16);\n"
          "    char *e_val;\n",
          uc);
    fputs("    size_t kl, vl;\n"
          "    if (!e_key) {\n"
          "      free(buf);\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    if (qp->params[i].value_is_encoded) {\n"
          "      e_val =\n"
          "          (c_cdd_strdup(qp->params[i].value, &_ast_strdup_8), "
          "_ast_strdup_8);\n"
          "    } else {\n"
          "      e_val = (url_encode_form(qp->params[i].value, "
          "&_ast_url_encode_form_17),\n"
          "               _ast_url_encode_form_17);\n",
          uc);
    fputs("    }\n"
          "    if (!e_val) {\n"
          "      free(e_key);\n"
          "      free(buf);\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    kl = strlen(e_key);\n"
          "    vl = strlen(e_val);\n"
          "    memcpy(ptr, e_key, kl);\n"
          "    ptr += kl;\n"
          "    *ptr++ = '=';\n"
          "    memcpy(ptr, e_val, vl);\n"
          "    ptr += vl;\n"
          "    if (i + 1 < qp->count)\n"
          "      *ptr++ = '&';\n"
          "    free(e_key);\n"
          "    free(e_val);\n"
          "  }\n",
          uc);
    fputs("  *ptr = '\\0';\n"
          "  *out_str = buf;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "static cdd_c_error_t\n"
          "    append_str(char **buf, size_t *len, size_t *cap, const char *s) "
          "{\n"
          "  size_t slen;\n"
          "  size_t need;\n"
          "  char *tmp;\n"
          "\n"
          "  if (!buf || !len || !cap || !s)\n"
          "    return CDD_C_ERROR_INVALID_ARGUMENT;\n"
          "\n"
          "  slen = strlen(s);\n"
          "  need = *len + slen + 1;\n"
          "  if (need > *cap) {\n",
          uc);
    fputs("    size_t new_cap = (*cap == 0) ? 64 : *cap * 2;\n"
          "    while (new_cap < need)\n"
          "      new_cap *= 2;\n"
          "    tmp = (char *)(size_t)realloc(*buf, new_cap);\n"
          "    if (!tmp) {\n"
          "      C_CDD_LOG_DEBUG(\"ENOMEM: OOM\\n\");\n"
          "      return CDD_C_ERROR_MEMORY;\n"
          "    }\n"
          "    *buf = tmp;\n"
          "    *cap = new_cap;\n"
          "  }\n"
          "  memcpy(*buf + *len, s, slen);\n"
          "  *len += slen;\n"
          "  (*buf)[*len] = '\\0';\n",
          uc);
    fputs("  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "static cdd_c_error_t\n"
          "    kv_value_to_string(const struct OpenAPI_KV *kv, char *buf, "
          "size_t buf_len,\n"
          "                       const char **_out_val) {\n"
          "  if (!kv) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "  switch (kv->type) {\n"
          "  case OA_KV_STRING: {\n"
          "    *_out_val = kv->value.s ? kv->value.s : NULL;\n",
          uc);
    fputs("    return CDD_C_SUCCESS;\n"
          "  }\n"
          "  case OA_KV_INTEGER:\n"
          "    if (!buf || buf_len == 0) {\n"
          "      *_out_val = NULL;\n"
          "      return CDD_C_SUCCESS;\n"
          "    }\n"
          "    sprintf_s_chk(buf, buf_len, \"%d\", kv->value.i);\n"
          "    {\n"
          "      *_out_val = buf;\n"
          "      return CDD_C_SUCCESS;\n"
          "    }\n"
          "  case OA_KV_NUMBER:\n"
          "    if (!buf || buf_len == 0) {\n"
          "      *_out_val = NULL;\n",
          uc);
    fputs("      return CDD_C_SUCCESS;\n"
          "    }\n"
          "    sprintf_s_chk(buf, buf_len, \"%g\", kv->value.n);\n"
          "    {\n"
          "      *_out_val = buf;\n"
          "      return CDD_C_SUCCESS;\n"
          "    }\n"
          "  case OA_KV_BOOLEAN: {\n"
          "    *_out_val = kv->value.b ? \"true\" : \"false\";\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "  default: {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "  }\n"
          "}\n"
          "\n"
          "/**\n",
          uc);
    fputs(" * @brief Executes the openapi kv join form operation.\n"
          " */\n"
          "cdd_c_error_t openapi_kv_join_form(const struct OpenAPI_KV *kvs, "
          "size_t n,\n"
          "                         const char *delim, int allow_reserved,\n"
          "                         char **_out_val) {\n"
          "  const char *_ast_kv_value_to_string_18 = NULL;\n"
          "  size_t i;\n"
          "  char *buf = NULL;\n"
          "  size_t len = 0;\n"
          "  size_t cap = 0;\n",
          uc);
    fputs("  char num_buf[64];\n"
          "  char *enc_key = NULL;\n"
          "  char *enc_val = NULL;\n"
          "  int (*enc_fn)(const char *, char **) =\n"
          "      allow_reserved ? url_encode_form_allow_reserved : "
          "url_encode_form;\n"
          "\n"
          "  if (!delim)\n"
          "    delim = \",\";\n"
          "\n"
          "  if (!kvs || n == 0) {\n"
          "    buf = (char *)(size_t)calloc(1, 1);\n"
          "    {\n"
          "      *_out_val = buf;\n"
          "      return CDD_C_SUCCESS;\n"
          "    }\n"
          "  }\n"
          "\n",
          uc);
    fputs("  for (i = 0; i < n; ++i) {\n"
          "    const char *raw_val;\n"
          "    if (!kvs[i].key)\n"
          "      continue;\n"
          "    raw_val = (kv_value_to_string(&kvs[i], num_buf, "
          "sizeof(num_buf),\n"
          "                                  &_ast_kv_value_to_string_18),\n"
          "               _ast_kv_value_to_string_18);\n"
          "    if (!raw_val)\n"
          "      continue;\n"
          "    enc_fn(kvs[i].key, &enc_key);\n"
          "    if (!enc_key)\n",
          uc);
    fputs("      goto oom;\n"
          "    enc_fn(raw_val, &enc_val);\n"
          "    if (!enc_val)\n"
          "      goto oom;\n"
          "    if (len > 0) {\n"
          "      if (append_str(&buf, &len, &cap, delim) != 0)\n"
          "        goto oom;\n"
          "    }\n"
          "    if (append_str(&buf, &len, &cap, enc_key) != 0)\n"
          "      goto oom;\n"
          "    if (append_str(&buf, &len, &cap, delim) != 0)\n"
          "      goto oom;\n",
          uc);
    fputs("    if (append_str(&buf, &len, &cap, enc_val) != 0)\n"
          "      goto oom;\n"
          "    free(enc_key);\n"
          "    free(enc_val);\n"
          "    enc_key = NULL;\n"
          "    enc_val = NULL;\n"
          "  }\n"
          "\n"
          "  if (!buf) {\n"
          "    buf = (char *)(size_t)calloc(1, 1);\n"
          "  }\n"
          "  {\n"
          "    *_out_val = buf;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "oom:\n"
          "  if (enc_key)\n"
          "    free(enc_key);\n"
          "  if (enc_val)\n"
          "    free(enc_val);\n",
          uc);
    fputs("  if (buf)\n"
          "    free(buf);\n"
          "  {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n",
          uc);
  }
  return CDD_C_SUCCESS;
}
