/**
 * @file client_gen_url_utils_c1.c
 * @brief url_utils.c (part 1) emission for OpenAPI client generator.
 */

/* clang-format off */
#include "c_cdd/safe_crt_msvc.h"

#include "routes/emit/client_gen_internal.h"
#include "c_cdd/log.h"
#include "c_cdd/safe_crt.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* clang-format on */

/**
 * @brief Emit url_utils.c (part 1) for installable package.
 */
cdd_c_error_t client_gen_emit_url_utils_c1(FILE *uc) {
  if (uc) {
    fputs("/**\n"
          " * @file url.c\n"
          " * @brief Implementation of RFC 3986 URL encoding and Query "
          "serialization.\n"
          " *\n"
          " * @author Samuel Marks\n"
          " */\n"
          "\n"
          "/* clang-format "
          "off */\n"
          "#include <ctype.h>\n"
          "#include <errno.h>\n"
          "#include <stdio.h>\n"
          "#include <stdlib.h>\n"
          "#include <string.h>\n"
          "\n"
          "#include \"functions/parse/str.h\" /* For c_cdd_strdup helpers */\n",
          uc);
    fputs("#include \"c_cdd/log.h\"\n#include \"url_utils.h\"\n"
          "/* clang-format "
          "on */\n"
          "\n"
          "/* Standard definitions for C89 compatibility */\n"
          "#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)\n"
          "#define sprintf_s_chk(buf, size, fmt, arg) sprintf_s(buf, size, "
          "fmt, arg)\n"
          "#else\n"
          "/* Naive fallback for non-MSVC C89 */\n"
          "/** @brief sprintf_s_chk macro */\n",
          uc);
    fputs("#define sprintf_s_chk(buf, size, fmt, arg) sprintf(buf, fmt, arg)\n"
          "#endif\n"
          "\n"
          "/**\n"
          " * @brief Check if a character is unreserved per RFC 3986 Section "
          "2.3.\n"
          " *\n"
          " * Unreserved characters: ALPHA, DIGIT, \"-\", \".\", \"_\", "
          "\"~\".\n"
          " */\n"
          "static int\n"
          "    is_unreserved(unsigned char c) {\n"
          "  if (isalnum(c))\n"
          "    return CDD_C_ERROR_UNKNOWN;\n",
          uc);
    fputs("  if (c == '-' || c == '.' || c == '_' || c == '~')\n"
          "    return CDD_C_ERROR_UNKNOWN;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Check if a character is reserved per RFC 3986 Section "
          "2.2.\n"
          " */\n"
          "static int\n"
          "    is_reserved(unsigned char c) {\n"
          "  switch (c) {\n"
          "  case ':':\n"
          "  case '/':\n"
          "  case '?':\n"
          "  case '#':\n"
          "  case '[':\n"
          "  case ']':\n"
          "  case '@':\n",
          uc);
    fputs("  case '!':\n"
          "  case '$':\n"
          "  case '&':\n"
          "  case '\\'':\n"
          "  case '(':\n"
          "  case ')':\n"
          "  case '*':\n"
          "  case '+':\n"
          "  case ',':\n"
          "  case ';':\n"
          "  case '=':\n"
          "    return CDD_C_ERROR_UNKNOWN;\n"
          "  default:\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n"
          "static int\n"
          "    is_hex(unsigned char c) {\n"
          "  return isxdigit(c) ? 1 : 0;\n"
          "}\n"
          "\n"
          "static int\n",
          uc);
    fputs("    is_pct_encoded(const char *p) {\n"
          "  if (!p)\n"
          "    return CDD_C_SUCCESS;\n"
          "  return (p[0] == '%' && is_hex((unsigned char)p[1]) &&\n"
          "          is_hex((unsigned char)p[2]));\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Convert a nibble to hexagonal character.\n"
          " */\n"
          "static cdd_c_error_t\n"
          "    to_hex(char code, char *_out_val) {\n"
          "  static const char hex[] = \"0123456789ABCDEF\";\n"
          "  {\n",
          uc);
    fputs("    *_out_val = hex[code & 15];\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n"
          "static int\n"
          "    is_unreserved_form(unsigned char c) {\n"
          "  if (isalnum(c))\n"
          "    return CDD_C_ERROR_UNKNOWN;\n"
          "  if (c == '-' || c == '.' || c == '_' || c == '*')\n"
          "    return CDD_C_ERROR_UNKNOWN;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Executes the url encode operation.\n"
          " */\n",
          uc);
    fputs("cdd_c_error_t url_encode(const char *str, char **_out_val) {\n"
          "  char _ast_to_hex_0;\n"
          "  char _ast_to_hex_1;\n"
          "  const char *p;\n"
          "  char *enc = NULL;\n"
          "  char *e;\n"
          "  size_t needed_len = 0;\n"
          "\n"
          "  if (!str) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  /* Pass 1: Calculate required length */\n"
          "  for (p = str; *p; p++) {\n",
          uc);
    fputs("    if (is_unreserved((unsigned char)*p)) {\n"
          "      needed_len++;\n"
          "    } else {\n"
          "      needed_len += 3; /* %HH */\n"
          "    }\n"
          "  }\n"
          "\n"
          "  /* Alloc */\n"
          "  enc = (char *)(size_t)malloc(needed_len + 1);\n"
          "  if (!enc) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  /* Pass 2: Encode */\n"
          "  e = enc;\n"
          "  for (p = str; *p; p++) {\n"
          "    unsigned char c = (unsigned char)*p;\n",
          uc);
    fputs("    if (is_unreserved(c)) {\n"
          "      *e++ = *p;\n"
          "    } else {\n"
          "      *e++ = '%';\n"
          "      *e++ = (to_hex(c >> 4, &_ast_to_hex_0), _ast_to_hex_0);\n"
          "      *e++ = (to_hex(c & 15, &_ast_to_hex_1), _ast_to_hex_1);\n"
          "    }\n"
          "  }\n"
          "  *e = '\\0';\n"
          "\n"
          "  {\n"
          "    *_out_val = enc;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n"
          "/**\n",
          uc);
    fputs(" * @brief Executes the url encode allow reserved operation.\n"
          " */\n"
          "cdd_c_error_t url_encode_allow_reserved(const char *str, char "
          "**_out_val) {\n"
          "  char _ast_to_hex_2;\n"
          "  char _ast_to_hex_3;\n"
          "  const char *p;\n"
          "  char *enc = NULL;\n"
          "  char *e;\n"
          "  size_t needed_len = 0;\n"
          "\n"
          "  if (!str) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n",
          uc);
    fputs("  /* Pass 1: Calculate required length */\n"
          "  for (p = str; *p; p++) {\n"
          "    if (*p == '%' && is_pct_encoded(p)) {\n"
          "      needed_len += 3;\n"
          "      p += 2;\n"
          "      continue;\n"
          "    }\n"
          "    if (is_unreserved((unsigned char)*p) || is_reserved((unsigned "
          "char)*p)) {\n"
          "      needed_len++;\n"
          "    } else {\n"
          "      needed_len += 3; /* %HH */\n"
          "    }\n"
          "  }\n"
          "\n",
          uc);
    fputs("  enc = (char *)(size_t)malloc(needed_len + 1);\n"
          "  if (!enc) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  e = enc;\n"
          "  for (p = str; *p; p++) {\n"
          "    unsigned char c = (unsigned char)*p;\n"
          "    if (*p == '%' && is_pct_encoded(p)) {\n"
          "      *e++ = *p++;\n"
          "      *e++ = *p++;\n"
          "      *e++ = *p;\n"
          "      continue;\n"
          "    }\n"
          "    if (is_unreserved(c) || is_reserved(c)) {\n",
          uc);
    fputs("      *e++ = *p;\n"
          "    } else {\n"
          "      *e++ = '%';\n"
          "      *e++ = (to_hex(c >> 4, &_ast_to_hex_2), _ast_to_hex_2);\n"
          "      *e++ = (to_hex(c & 15, &_ast_to_hex_3), _ast_to_hex_3);\n"
          "    }\n"
          "  }\n"
          "  *e = '\\0';\n"
          "  {\n"
          "    *_out_val = enc;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Executes the url encode form operation.\n"
          " */\n",
          uc);
    fputs("cdd_c_error_t url_encode_form(const char *str, char **_out_val) "
          "{\n"
          "  char _ast_to_hex_4;\n"
          "  char _ast_to_hex_5;\n"
          "  const char *p;\n"
          "  char *enc = NULL;\n"
          "  char *e;\n"
          "  size_t needed_len = 0;\n"
          "\n"
          "  if (!str) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  for (p = str; *p; p++) {\n"
          "    unsigned char c = (unsigned char)*p;\n"
          "    if (c == ' ') {\n",
          uc);
    fputs("      needed_len++;\n"
          "    } else if (is_unreserved_form(c)) {\n"
          "      needed_len++;\n"
          "    } else {\n"
          "      needed_len += 3;\n"
          "    }\n"
          "  }\n"
          "\n"
          "  enc = (char *)(size_t)malloc(needed_len + 1);\n"
          "  if (!enc) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  e = enc;\n"
          "  for (p = str; *p; p++) {\n"
          "    unsigned char c = (unsigned char)*p;\n"
          "    if (c == ' ') {\n",
          uc);
    fputs("      *e++ = '+';\n"
          "    } else if (is_unreserved_form(c)) {\n"
          "      *e++ = *p;\n"
          "    } else {\n"
          "      *e++ = '%';\n"
          "      *e++ = (to_hex(c >> 4, &_ast_to_hex_4), _ast_to_hex_4);\n"
          "      *e++ = (to_hex(c & 15, &_ast_to_hex_5), _ast_to_hex_5);\n"
          "    }\n"
          "  }\n"
          "  *e = '\\0';\n"
          "  {\n"
          "    *_out_val = enc;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n"
          "/**\n",
          uc);
    fputs(" * @brief Executes the url encode form allow reserved operation.\n"
          " */\n"
          "cdd_c_error_t url_encode_form_allow_reserved(const char *str, "
          "char "
          "**_out_val) {\n"
          "  char _ast_to_hex_6;\n"
          "  char _ast_to_hex_7;\n"
          "  char _ast_to_hex_8;\n"
          "  char _ast_to_hex_9;\n"
          "  const char *p;\n"
          "  char *enc = NULL;\n"
          "  char *e;\n"
          "  size_t needed_len = 0;\n"
          "\n"
          "  if (!str) {\n"
          "    *_out_val = NULL;\n",
          uc);
    fputs("    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  for (p = str; *p; p++) {\n"
          "    unsigned char c = (unsigned char)*p;\n"
          "    if (c == ' ') {\n"
          "      needed_len++;\n"
          "    } else if (is_pct_encoded(p)) {\n"
          "      needed_len += 3;\n"
          "      p += 2;\n"
          "    } else if (is_unreserved_form(c) || is_reserved(c)) {\n"
          "      if (c == '&' || c == '=' || c == '+') {\n"
          "        needed_len += 3;\n"
          "      } else {\n",
          uc);
    fputs("        needed_len++;\n"
          "      }\n"
          "    } else {\n"
          "      needed_len += 3;\n"
          "    }\n"
          "  }\n"
          "\n"
          "  enc = (char *)(size_t)malloc(needed_len + 1);\n"
          "  if (!enc) {\n"
          "    *_out_val = NULL;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "\n"
          "  e = enc;\n"
          "  for (p = str; *p; p++) {\n"
          "    unsigned char c = (unsigned char)*p;\n"
          "    if (c == ' ') {\n"
          "      *e++ = '+';\n"
          "    } else if (is_pct_encoded(p)) {\n",
          uc);
    fputs("      *e++ = *p++;\n"
          "      *e++ = *p++;\n"
          "      *e++ = *p;\n"
          "    } else if (is_unreserved_form(c) || is_reserved(c)) {\n"
          "      if (c == '&' || c == '=' || c == '+') {\n"
          "        *e++ = '%';\n"
          "        *e++ = (to_hex(c >> 4, &_ast_to_hex_6), _ast_to_hex_6);\n"
          "        *e++ = (to_hex(c & 15, &_ast_to_hex_7), _ast_to_hex_7);\n"
          "      } else {\n"
          "        *e++ = *p;\n"
          "      }\n"
          "    } else {\n",
          uc);
    fputs("      *e++ = '%';\n"
          "      *e++ = (to_hex(c >> 4, &_ast_to_hex_8), _ast_to_hex_8);\n"
          "      *e++ = (to_hex(c & 15, &_ast_to_hex_9), _ast_to_hex_9);\n"
          "    }\n"
          "  }\n"
          "  *e = '\\0';\n"
          "  {\n"
          "    *_out_val = enc;\n"
          "    return CDD_C_SUCCESS;\n"
          "  }\n"
          "}\n"
          "\n"
          "/**\n"
          " * @brief Executes the url query init operation.\n"
          " */\n"
          "cdd_c_error_t url_query_init(struct UrlQueryParams *qp) {\n",
          uc);
    fputs("  if (!qp)\n"
          "    return CDD_C_ERROR_INVALID_ARGUMENT;\n"
          "  qp->params = NULL;\n"
          "  qp->count = 0;\n"
          "  qp->capacity = 0;\n"
          "  return CDD_C_SUCCESS;\n"
          "}\n"
          "\n",
          uc);
  }
  return CDD_C_SUCCESS;
}
