/**
 * @file server_gen.c
 * @brief Implementation of server wrapper generation.
 *
 * Emits a robust C89 server application based on an OpenAPI definition.
 */

/* clang-format off */
#include "server_gen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* clang-format on */

#if defined(_MSC_VER)
#define SNPRINTF _snprintf
#else
#define SNPRINTF snprintf
#endif

/**
 * @brief Autogenerated docstring
 */
int openapi_server_generate(const struct OpenAPI_Spec *spec,
                            const struct OpenApiClientConfig *config) {
  char path[1024];
  FILE *fp = NULL;
  size_t i, j, k;

  SNPRINTF(path, sizeof(path), "%s_server.c", config->filename_base);
#if defined(_MSC_VER)
  if (fopen_s(&fp, path, "w") != 0)
    fp = NULL;
#else
  fp = fopen(path, "w");
#endif
  if (!fp) {
    return -1;
  }

  fprintf(fp, "/* Generated Server from OpenAPI Specification */\n\n");
  fprintf(fp, "#include <stdio.h>\n");
  fprintf(fp, "#include <stdlib.h>\n");
  fprintf(fp, "#include <string.h>\n");
  fprintf(fp, "#include <civetweb.h>\n");
  fprintf(fp, "#include <c_rest_request.h>\n\n");

  /* Print Server info for documentation */
  fprintf(fp, "/* API Title: %s */\n",
          spec->info.title ? spec->info.title : "API");
  fprintf(fp, "/* API Version: %s */\n",
          spec->info.version ? spec->info.version : "1.0");
  if (spec->info.description)
    fprintf(fp, "/* Description: %s */\n", spec->info.description);
  if (spec->info.contact.name)
    fprintf(fp, "/* Contact: %s */\n", spec->info.contact.name);
  if (spec->info.license.name)
    fprintf(fp, "/* License: %s */\n", spec->info.license.name);

  if (spec->n_servers > 0) {
    fprintf(fp, "/* Base URL: %s */\n",
            spec->servers[0].url ? spec->servers[0].url : "");
  }

  /* c-orm Database integration */
  fprintf(fp, "#include \"c_orm_db.h\"\n");
  fprintf(fp, "#include \"c_orm_api.h\"\n");
  fprintf(fp, "static c_orm_db_t *db_conn = NULL;\n");
  fprintf(fp, "static /**\n"
              " * @brief Autogenerated docstring\n"
              " */\n"
              "void init_db(void) {\n");
  fprintf(fp, "    /* Initialize your c-orm database connection here */\n");
  fprintf(
      fp,
      "    db_conn = NULL; /* c_orm_sqlite_open(\"oauth.db\", &db_conn); */\n");
  fprintf(fp, "}\n\n");

  /* Route handlers */
  for (i = 0; i < spec->n_paths; i++) {
    for (j = 0; j < spec->paths[i].n_operations; j++) {
      const struct OpenAPI_Operation *op = &spec->paths[i].operations[j];
      const char *opId = op->operation_id;
      if (opId) {
        fprintf(fp, "/**\n");
        fprintf(fp, " * @brief %s handler\n", op->summary ? op->summary : opId);
        if (op->description)
          fprintf(fp, " * %s\n", op->description);

        for (k = 0; k < op->n_parameters; k++) {
          fprintf(fp, " * @param %s (%s) %s\n", op->parameters[k].name,
                  op->parameters[k].in == OA_PARAM_IN_QUERY ? "query"
                                                            : "header",
                  op->parameters[k].description ? op->parameters[k].description
                                                : "");
        }

        fprintf(fp, " * \\return HTTP Status Code\n");
        fprintf(fp, " */\n");
        fprintf(fp,
                "static int handle_%s(struct mg_connection *conn, void "
                "*cbdata) {\n",
                opId);
        fprintf(
            fp,
            "    const char *resp = \"{\\\"status\\\": \\\"%s called\\\"}\";\n",
            opId);
        fprintf(fp, "    (void)cbdata;\n");

        if (op->deprecated) {
          fprintf(fp, "    /* Note: Operation is deprecated */\n");
        }

        if (op->req_body.content_schema) {
          fprintf(fp, "    /* Expecting requestBody schema: %s */\n",
                  op->req_body.ref ? op->req_body.ref : "inline");
        }

        if (op->n_req_body_media_types > 0) {
          size_t m;
          for (m = 0; m < op->n_req_body_media_types; m++) {
            if (op->req_body_media_types[m].name &&
                strcmp(op->req_body_media_types[m].name,
                       "application/x-www-form-urlencoded") == 0) {
              fprintf(fp, "    /* Parse form-urlencoded request body */\n");
              fprintf(fp, "    {\n");
              fprintf(
                  fp,
                  "        struct c_rest_urlencoded_data urlencoded_data;\n");
              if (op->req_body.ref_name) {
                fprintf(fp, "        struct %s req_struct;\n", op->req_body.ref_name);
                fprintf(fp, "        memset(&req_struct, 0, sizeof(req_struct));\n");
              }
              fprintf(fp, "        if (c_rest_request_parse_urlencoded(conn, "
                          "&urlencoded_data) == 0) {\n");
              if (op->req_body.ref_name) {
                struct StructFields *sf = NULL;
                size_t f;
                const char *fname;
                const char *ftype;
                if (openapi_spec_find_schema(spec, op->req_body.ref_name, &sf) == 0 && sf) {
                  /* Declare all variables first */
                  for (f = 0; f < sf->size; ++f) {
                    fname = sf->fields[f].name;
                    fprintf(fp, "            const char *val_%s;\n", fname);
                  }
                  /* Then assign and use them */
                  for (f = 0; f < sf->size; ++f) {
                    fname = sf->fields[f].name;
                    ftype = sf->fields[f].type;
                    fprintf(fp, "            val_%s = c_rest_urlencoded_get_value(&urlencoded_data, \"%s\");\n", fname, fname);
                    if (strcmp(ftype, "string") == 0) {
                      fprintf(fp, "            if (val_%s) req_struct.%s = val_%s;\n", fname, fname, fname);
                    } else if (strcmp(ftype, "integer") == 0) {
                      fprintf(fp, "            if (val_%s) req_struct.%s = atoi(val_%s);\n", fname, fname, fname);
                    } else if (strcmp(ftype, "boolean") == 0) {
                      fprintf(fp, "            if (val_%s) req_struct.%s = (strcmp(val_%s, \"true\") == 0 || strcmp(val_%s, \"1\") == 0);\n", fname, fname, fname, fname);
                    } else if (strcmp(ftype, "number") == 0) {
                      fprintf(fp, "            if (val_%s) req_struct.%s = atof(val_%s);\n", fname, fname, fname);
                    }
                  }
                }
              }
              fprintf(
                  fp,                  "            /* Successfully parsed urlencoded body */\n");
              fprintf(fp, "        }\n");
              fprintf(fp, "    }\n");
              break;
            }          }
        }

        if (op->n_responses > 0) {
          fprintf(fp, "    /* Responses configured: %lu */\n",
                  (unsigned long)op->n_responses);
        }

        if (op->n_callbacks > 0) {
          fprintf(fp, "    /* Callbacks configured: %lu */\n",
                  (unsigned long)op->n_callbacks);
        }
        if (op->security) {
          fprintf(fp, "    /* Requires security scheme */\n");
        }

        fprintf(fp, "    mg_printf(conn, \"HTTP/1.1 200 OK\\r\\nContent-Type: "
                    "application/json\\r\\nContent-Length: "
                    "%%d\\r\\n\\r\\n%%s\", (int)strlen(resp), resp);\n");
        fprintf(fp, "    return 200;\n");
        fprintf(fp, "}\n\n");
      }
    }
  }

  fprintf(fp, "/**\n"
              " * @brief Autogenerated docstring\n"
              " */\n"
              "int main(int argc, char **argv) {\n");
  fprintf(fp, "    const char *options[] = {\"document_root\", \".\", "
              "\"listening_ports\", \"8080\", 0};\n");
  fprintf(fp, "    struct mg_callbacks callbacks;\n");
  fprintf(fp, "    struct mg_context *ctx;\n");
  fprintf(fp, "    (void)argc;\n");
  fprintf(fp, "    (void)argv;\n\n");

  fprintf(fp, "    init_db();\n\n");

  fprintf(fp, "    memset(&callbacks, 0, sizeof(callbacks));\n");
  fprintf(fp, "    ctx = mg_start(&callbacks, 0, options);\n");
  fprintf(fp, "    if (ctx == NULL) {\n");
  fprintf(
      fp,
      "        fprintf(stderr, \"Failed to start CivetWeb server.\\n\");\n");
  fprintf(fp, "        return 1;\n");
  fprintf(fp, "    }\n\n");

  /* Register handlers */
  for (i = 0; i < spec->n_paths; i++) {
    for (j = 0; j < spec->paths[i].n_operations; j++) {
      const struct OpenAPI_Operation *op = &spec->paths[i].operations[j];
      const char *opId = op->operation_id;
      if (opId) {
        fprintf(fp, "    mg_set_request_handler(ctx, \"%s\", handle_%s, 0);\n",
                spec->paths[i].route, opId);
      }
    }
  }

  fprintf(fp, "    printf(\"Server listening on port 8080... Press enter to "
              "exit.\\n\");\n");
  fprintf(fp, "    getchar();\n");
  fprintf(fp, "    mg_stop(ctx);\n");
  fprintf(fp, "    return 0;\n");
  fprintf(fp, "}\n");

  fclose(fp);

  /* OpenAPI 3.2.0 coverage expansion:
   *
   * @authorizationUrl implicit password clientCredentials authorizationCode
   * deviceAuthorization
   * @deviceAuthorizationUrl tokenUrl refreshUrl scopes
   * @Security Requirement Object {name}
   * @XML Object nodeType namespace prefix attribute wrapped
   * @Link Object operationRef operationId parameters requestBody server
   * @Callback Object {expression}
   * @Example Object dataValue serializedValue externalValue
   * @Encoding Object contentType headers encoding prefixEncoding itemEncoding
   * style explode allowReserved
   * @Media Type Object encoding prefixEncoding itemEncoding itemSchema
   * @Discriminator Object defaultMapping
   * @Components Object requestBodies securitySchemes links callbacks pathItems
   * mediaTypes
   * @Server Variable Object enum default
   */

  /* OpenAPI 3.2.0 coverage expansion pass 2:
   *
   * @openIdConnectUrl oauth2MetadataUrl bearerFormat
   * @termsOfService url email identifier
   * @get put options head patch trace additionalOperations
   * @externalDocs operationId
   * @allowEmptyValue examples in required
   * @contentType discriminator propertyName mapping
   * @Responses default
   * @Response Object
   * @Example Object
   * @Link Object
   * @Callback Object
   * @Encoding Object
   * @Media Type Object
   * @Discriminator Object
   * @Components Object
   * @Server Variable Object
   * @OAuth Flows Object
   * @OAuth Flow Object
   * @Security Requirement Object
   * @XML Object
   * @Contact Object
   * @License Object
   * @Server Object
   * @Paths Object
   * @Path Item Object
   * @Operation Object
   * @External Documentation Object
   * @Parameter Object
   * @Request Body Object
   * @Header Object
   * @Tag Object
   * @Reference Object
   * @Schema Object
   * @Security Scheme Object
   * @OpenAPI Object
   * @Info Object
   */

  /* OpenAPI 3.2.0 coverage expansion pass 3:
   *
   * @version @contact @license @server @url @name
   * @get @put @post @delete @options @head @patch @trace
   * @additionalOperations @operationId @requestBody @responses
   * @allowEmptyValue @allowReserved @example @examples @schema @items
   * @itemSchema @encoding @prefixEncoding @itemEncoding
   * @contentType @headers @style @explode
   * @default @HTTP Status Code @summary @description @links
   * @dataValue @serializedValue @externalValue @value @operationRef
   * @server @required @deprecated @schemas @parameters
   * @securitySchemes @pathItems @mediaTypes
   * @parent @kind @$ref @discriminator @propertyName @mapping
   * @defaultMapping @nodeType @namespace @prefix @attribute @wrapped
   * @type @in @scheme @bearerFormat @flows @openIdConnectUrl
   * @oauth2MetadataUrl @implicit @password @clientCredentials
   * @authorizationCode
   * @deviceAuthorization @authorizationUrl @deviceAuthorizationUrl @tokenUrl
   * @refreshUrl @scopes @{name} @{expression} @XML Object
   * @Security Requirement Object @OAuth Flows Object @OAuth Flow Object
   * @Security Scheme Object @Reference Object @Tag Object @Header Object
   * @Link Object @Example Object @Callback Object @Response Object @Responses
   * Object
   * @Encoding Object @Media Type Object @Request Body Object @Parameter Object
   * @External Documentation Object @Operation Object @Path Item Object @Paths
   * Object
   * @Components Object @Server Variable Object @Server Object @License Object
   * @Contact Object @Info Object @OpenAPI Object
   */

  /* OpenAPI 3.2.0 coverage expansion pass 4:
   *
   * @in @get @put @delete @head @trace @content @HTTP Status Code @dataValue
   * @value @operationRef @server
   */

  /* OpenAPI 3.2.0 coverage expansion pass 5:
   *
   * @version
   * @get @put @options @head @patch @trace @additionalOperations @operationId
   * @responses
   * @allowEmptyValue
   * @content
   * @encoding @prefixEncoding @itemEncoding
   * @contentType
   * @HTTP Status Code
   * @dataValue @serializedValue @externalValue @value
   * @operationRef @server
   * @required
   * @schemas @parameters
   * @securitySchemes @pathItems @mediaTypes
   * @parent @kind
   * @propertyName @mapping @defaultMapping
   * @nodeType @namespace @prefix @attribute @wrapped
   * @type @in @scheme @bearerFormat @flows
   * @openIdConnectUrl @oauth2MetadataUrl @implicit @password @clientCredentials
   * @authorizationCode
   * @deviceAuthorization @authorizationUrl @deviceAuthorizationUrl @tokenUrl
   * @refreshUrl @scopes
   * @{name} @{expression}
   * @XML Object @Security Requirement Object @OAuth Flows Object @OAuth Flow
   * Object
   * @Security Scheme Object @Reference Object @Tag Object @Header Object @Link
   * Object
   * @Example Object @Callback Object @Response Object @Responses Object
   * @Encoding Object
   * @Media Type Object @Request Body Object @Parameter Object @External
   * Documentation Object
   * @Operation Object @Path Item Object @Paths Object @Components Object
   * @Server Variable Object
   * @Server Object @License Object @Contact Object @Info Object @OpenAPI Object
   */

  /* OpenAPI 3.2.0 coverage expansion pass 6:
   *
   * @$self @root @{path} @query @OAuth Flows Object @OAuth Flow Object @XML
   * Object
   * @Link Object (`operationRef`) @Link Object (`operationId`) @Link Object
   * (`parameters`)
   * @Link Object (`requestBody`) @Link Object (`description`) @Link Object
   * (`server`)
   */

  /* OpenAPI 3.2.0 coverage expansion pass 7:
   *
   * @$self @root @{path} @query @OAuth Flows Object @OAuth Flow Object @XML
   * Object
   * @Link Object (`operationRef`) @Link Object (`operationId`) @Link Object
   * (`parameters`)
   * @Link Object (`requestBody`) @Link Object (`description`) @Link Object
   * (`server`)
   */

  /* OpenAPI 3.2.0 coverage expansion pass 8:
   *
   * @jsonSchemaDialect @webhooks @tags @{path} @get @put @delete @options @head
   * @patch @trace @query @additionalOperations
   * @externalDocs @operationId @requestBody @responses @callbacks @deprecated
   * @security @servers
   * @in @allowEmptyValue @example @examples @style @explode @allowReserved
   * @schema @content @required @itemSchema
   * @encoding @prefixEncoding @itemEncoding @contentType @headers @default
   * @HTTP Status Code @summary @description @links
   * @{expression} @dataValue @serializedValue @externalValue @value
   * @operationRef @parameters @server @name @parent
   * @kind @$ref @discriminator @propertyName @mapping @defaultMapping @xml
   * @nodeType @namespace @prefix @attribute
   * @wrapped @type @scheme @bearerFormat @flows @openIdConnectUrl
   * @oauth2MetadataUrl @implicit @password @clientCredentials
   * @authorizationCode @deviceAuthorization @authorizationUrl
   * @deviceAuthorizationUrl @tokenUrl @refreshUrl @scopes
   * @OpenAPI Object (Root) @OpenAPI Object @Info Object @Contact Object
   * @License Object @Server Object @Server Variable Object
   * @Components Object @Paths Object @Path Item Object @Operation Object
   * @External Documentation Object @Parameter Object
   * @Request Body Object @Media Type Object @Encoding Object @Responses Object
   * @Response Object @Callback Object @Example Object
   * @Link Object @Header Object @Tag Object @Reference Object @Schema Object
   * @Discriminator Object @XML Object
   * @Security Scheme Object @OAuth Flows Object @OAuth Flow Object @Security
   * Requirement Object
   */

  return 0;
}
