#ifndef SERVER_JSON_RPC_H
#define SERVER_JSON_RPC_H
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**
 * @brief Autogenerated docstring
 */
int server_json_rpc_main(int argc, char **argv);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif
