#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "functions/emit/diff_generator.h"

/* Simplified diff engine. In a real scenario we'd do a line-by-line diff.
   For CST rewrites, we can emit the old code and the new code and run a simple delta.
   Since building a diff algorithm from scratch is complex, we will approximate a diff
   by outputting the original tokens within a 3-line context of the patch, and the replaced text.
*/

/**
 * @brief Autogenerated docstring
 */
int patch_list_generate_diff(const struct TokenList *tokens,
                             const struct PatchList *list,
                             const char *filename,
                             char **out_diff) {
  char *diff_buf = NULL;
  size_t diff_cap = 4096;
  size_t diff_len = 0;
  size_t i;

  if (!tokens || !list || !filename || !out_diff)
    return EINVAL;

  diff_buf = malloc(diff_cap);
  if (!diff_buf)
    return ENOMEM;

  diff_buf[0] = '\0';
  
  if (list->size == 0) {
    *out_diff = diff_buf;
    return 0;
  }

  /* Print header */
  diff_len += sprintf(diff_buf + diff_len, "--- a/%s\n+++ b/%s\n", filename, filename);

  for (i = 0; i < list->size; ++i) {
    const struct Patch *p = &list->patches[i];
    /* Find line numbers to give context */
    /* This is a simplification; we'll output a chunk */
    diff_len += sprintf(diff_buf + diff_len, "@@ -patch %d @@\n", (int)i);
    
    /* Emit old tokens (we prefix with '-') */
    diff_len += sprintf(diff_buf + diff_len, "-");
    {
      size_t j;
      for (j = p->start_token_idx; j < p->end_token_idx; ++j) {
        if (diff_len + tokens->tokens[j].length + 10 > diff_cap) {
          diff_cap *= 2;
          diff_buf = realloc(diff_buf, diff_cap);
          if (!diff_buf) return ENOMEM;
        }
        memcpy(diff_buf + diff_len, tokens->tokens[j].start, tokens->tokens[j].length);
        diff_len += tokens->tokens[j].length;
      }
    }
    diff_len += sprintf(diff_buf + diff_len, "\n");
    
    /* Emit new tokens (we prefix with '+') */
    if (diff_len + strlen(p->text) + 10 > diff_cap) {
      diff_cap = diff_cap * 2 + strlen(p->text);
      diff_buf = realloc(diff_buf, diff_cap);
      if (!diff_buf) return ENOMEM;
    }
    diff_len += sprintf(diff_buf + diff_len, "+%s\n", p->text);
  }

  *out_diff = diff_buf;
  return 0;
}
