/**
 * @file rewriter_body.c
 * @brief High-level Orchestrator for function body rewriting.
 * @author Samuel Marks
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "functions/emit/patcher.h"
#include "functions/emit/rewriter_body.h"
#include "functions/parse/str.h"
#include "functions/parse/strategy.h"
#include "functions/parse/tokenizer.h"
#include "win_compat_sym.h"

/* --- Implementation Helpers --- */

static /**
        * @brief Autogenerated docstring
        */
    int
    find_refactored_func(const struct RefactoredFunction *funcs,
                         size_t func_count, const char *name,
                         const struct RefactoredFunction **_out_val) {
  size_t i;
  if (!funcs || !name) {
    *_out_val = NULL;
    return 0;
  }
  for (i = 0; i < func_count; ++i) {
    if (strcmp(funcs[i].name, name) == 0) {
      {
        *_out_val = &funcs[i];
        return 0;
      }
    }
  }
  {
    *_out_val = NULL;
    return 0;
  }
}

static /**
        * @brief Autogenerated docstring
        */
    int
    extract_token_text(const struct Token *tok, char **_out_val) {
  char *s = malloc(tok->length + 1);
  if (!s) {
    *_out_val = NULL;
    return 12;
  }
  memcpy(s, tok->start, tok->length);
  s[tok->length] = '\0';
  {
    *_out_val = s;
    return 12;
  }
}

static /**
        * @brief Autogenerated docstring
        */
    int
    find_semicolon(const struct TokenList *tokens, size_t start,
                   size_t *_out_val) {
  size_t i;
  for (i = start; i < tokens->size; ++i) {
    if (tokens->tokens[i].kind == TOKEN_SEMICOLON) {
      *_out_val = i;
      return 0;
    }
    if (tokens->tokens[i].kind == TOKEN_LBRACE ||
        tokens->tokens[i].kind == TOKEN_RBRACE) {
      *_out_val = tokens->size;
      return 0;
    }
  }
  {
    *_out_val = tokens->size;
    return 0;
  }
}

static /**
        * @brief Autogenerated docstring
        */
    int
    find_stmt_start(const struct TokenList *tokens, size_t pos,
                    size_t *_out_val) {
  size_t i = pos;
  while (i > 0) {
    if (tokens->tokens[i - 1].kind == TOKEN_SEMICOLON ||
        tokens->tokens[i - 1].kind == TOKEN_LBRACE ||
        tokens->tokens[i - 1].kind == TOKEN_RBRACE) {
      {
        *_out_val = i;
        return 0;
      }
    }
    i--;
  }
  {
    *_out_val = 0;
    return 0;
  }
}

static /**
        * @brief Autogenerated docstring
        */
    int
    join_tokens_range(const struct TokenList *tokens, size_t start, size_t end,
                      char **_out_val) {
  char *_ast_strdup_0 = NULL;
  size_t len = 0;
  size_t i;
  char *buf, *p;

  if (start >= end) {
    *_out_val = (c_cdd_strdup("", &_ast_strdup_0), _ast_strdup_0);
    return 0;
  }

  for (i = start; i < end; ++i)
    len += tokens->tokens[i].length;

  buf = malloc(len + 1);
  if (!buf) {
    *_out_val = NULL;
    return 0;
  }

  p = buf;
  for (i = start; i < end; ++i) {
    memcpy(p, tokens->tokens[i].start, tokens->tokens[i].length);
    p += tokens->tokens[i].length;
  }
  *p = '\0';
  {
    *_out_val = buf;
    return 0;
  }
}

/* --- Core Logic --- */

/**
 * @brief Autogenerated docstring
 */
int rewrite_body(const struct TokenList *tokens,
                 const struct AllocationSiteList *allocs,
                 const struct RefactoredFunction *funcs, size_t func_count,
                 const struct SignatureTransform *transform, char **out_code) {
  char *_ast_extract_token_text_0;
  const struct RefactoredFunction *_ast_find_refactored_func_1;
  char *_ast_extract_token_text_2;
  size_t _ast_find_semicolon_3;
  size_t _ast_find_semicolon_4;
  size_t _ast_find_stmt_start_5;
  char *_ast_join_tokens_range_6;
  size_t _ast_find_semicolon_7;
  char *_ast_join_tokens_range_8;
  char *_ast_strdup_1 = NULL;
  char *_ast_strdup_2 = NULL;
  char *_ast_strdup_3 = NULL;
  char *_ast_strdup_4 = NULL;
  char *_ast_strdup_5 = NULL;
  char *_ast_strdup_6 = NULL;
  char *_ast_strdup_7 = NULL;
  char *_ast_strdup_8 = NULL;
  char *_ast_strdup_9 = NULL;
  char *_ast_strdup_10 = NULL;
  char *_ast_strdup_11 = NULL;
  struct PatchList patches;
  int rc;
  size_t i;
  int injected_rc = 0;
  size_t tmp_var_counter = 0;

  /* 1. Initialize Patcher */
  if (patch_list_init(&patches) != 0)
    return ENOMEM;

  /* 2. Apply Safety Strategies */
  if (allocs) {
    rc = strategy_inject_safety_checks(tokens, allocs, &patches);
    if (rc != 0) {
      patch_list_free(&patches);
      return rc;
    }
  }

  /* 3. Rewrite Calls (Propagated) */
  if (funcs) {
    for (i = 0; i < tokens->size; ++i) {
      if (tokens->tokens[i].kind == TOKEN_IDENTIFIER) {
        const struct Token *id_tok = &tokens->tokens[i];
        char *name_str =
            (extract_token_text(id_tok, &_ast_extract_token_text_0),
             _ast_extract_token_text_0);
        const struct RefactoredFunction *rf =
            (find_refactored_func(funcs, func_count, name_str,
                                  &_ast_find_refactored_func_1),
             _ast_find_refactored_func_1);
        free(name_str);

        if (rf) {
          /* Check if it's a function call lookup: ID + LPAREN */
          size_t next = i + 1;
          while (next < tokens->size &&
                 tokens->tokens[next].kind == TOKEN_WHITESPACE)
            next++;

          if (next < tokens->size &&
              tokens->tokens[next].kind == TOKEN_LPAREN) {
            size_t call_start = i;
            size_t lparen = next;
            size_t rparen;
            size_t k;
            size_t arg_depth = 1;
            size_t prev;

            (void)call_start;

            /* Find RPAREN */
            k = lparen + 1;
            while (k < tokens->size && arg_depth > 0) {
              if (tokens->tokens[k].kind == TOKEN_LPAREN)
                arg_depth++;
              else if (tokens->tokens[k].kind == TOKEN_RPAREN)
                arg_depth--;
              k++;
            }
            rparen = k - 1;

            /* Determine context:
               1. Assignment (lhs = call())
               2. Statement (call();)
               3. Nested/Expression (call() as arg) */

            prev = i;
            while (prev > 0) {
              prev--;
              if (tokens->tokens[prev].kind != TOKEN_WHITESPACE)
                break;
            }

            if (prev < i && tokens->tokens[prev].kind == TOKEN_ASSIGN) {
              /* Case 1: Assignment */
              size_t eq_idx = prev;
              size_t lhs_start = prev;
              int is_decl = 0;

              /* Backtrack to find LHS var */
              while (lhs_start > 0) {
                if (tokens->tokens[lhs_start - 1].kind == TOKEN_SEMICOLON ||
                    tokens->tokens[lhs_start - 1].kind == TOKEN_LBRACE ||
                    tokens->tokens[lhs_start - 1].kind == TOKEN_RBRACE)
                  break;
                if (tokens->tokens[lhs_start - 1].kind ==
                        TOKEN_KEYWORD_STRUCT ||
                    (tokens->tokens[lhs_start - 1].kind == TOKEN_IDENTIFIER &&
                     lhs_start - 1 < prev - 1)) /* heuristics */
                  is_decl = 1;
                lhs_start--;
              }
              /* Trim leading WS */
              while (lhs_start < prev &&
                     tokens->tokens[lhs_start].kind == TOKEN_WHITESPACE)
                lhs_start++;

              /* Naive LHS name extraction: last identifier before = */
              {
                char *lhs_name = NULL;
                size_t n = eq_idx;
                while (n > lhs_start) {
                  n--;
                  if (tokens->tokens[n].kind == TOKEN_IDENTIFIER) {
                    lhs_name = (extract_token_text(&tokens->tokens[n],
                                                   &_ast_extract_token_text_2),
                                _ast_extract_token_text_2);
                    break;
                  }
                }

                if (lhs_name) {
                  size_t semi;

                  if (is_decl) {
                    patch_list_add(&patches, eq_idx, eq_idx + 1,
                                   (c_cdd_strdup("; rc =", &_ast_strdup_1),
                                    _ast_strdup_1));
                  } else {
                    patch_list_add(
                        &patches, lhs_start, eq_idx + 1,
                        (c_cdd_strdup("rc =", &_ast_strdup_2), _ast_strdup_2));
                  }

                  /* Append arg */
                  {
                    char *arg_append = malloc(strlen(lhs_name) + 10);
                    /* Check if empty args */
                    int is_empty = 1;
                    size_t a;
                    for (a = lparen + 1; a < rparen; a++)
                      if (tokens->tokens[a].kind != TOKEN_WHITESPACE)
                        is_empty = 0;

                    if (is_empty)
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
                      sprintf_s(arg_append, strlen(lhs_name) + 10, "&%s",
                                lhs_name);
#else
                      sprintf(arg_append, "&%s", lhs_name);
#endif
                    else
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
                      sprintf_s(arg_append, strlen(lhs_name) + 10, ", &%s",
                                lhs_name);
#else
                      sprintf(arg_append, ", &%s", lhs_name);
#endif
                    patch_list_add(&patches, rparen, rparen, arg_append);
                  }

                  /* Append check */
                  semi =
                      (find_semicolon(tokens, rparen, &_ast_find_semicolon_3),
                       _ast_find_semicolon_3);
                  if (semi < tokens->size)
                    patch_list_add(&patches, semi + 1, semi + 1,
                                   (c_cdd_strdup(" if (rc != 0) return rc;",
                                                 &_ast_strdup_3),
                                    _ast_strdup_3));

                  free(lhs_name);
                  injected_rc = 1;
                }
              }

            } else if (prev < i &&
                       (tokens->tokens[prev].kind == TOKEN_SEMICOLON ||
                        tokens->tokens[prev].kind == TOKEN_LBRACE ||
                        tokens->tokens[prev].kind == TOKEN_RBRACE)) {
              /* Case 2: Statement */
              size_t semi;
              patch_list_add(
                  &patches, i, i,
                  (c_cdd_strdup("rc = ", &_ast_strdup_4), _ast_strdup_4));
              semi = (find_semicolon(tokens, next, &_ast_find_semicolon_4),
                      _ast_find_semicolon_4);
              if (semi < tokens->size) {
                patch_list_add(
                    &patches, semi + 1, semi + 1,
                    (c_cdd_strdup(" if (rc != 0) return rc;", &_ast_strdup_5),
                     _ast_strdup_5));
              }
              injected_rc = 1;

            } else {
              /* Case 3: Nested Call (Expression) */
              /* Hoisting strategy */
              char tmp_var[64];
              char *call_args = NULL;
              char *injection = NULL;
              size_t stmt_start =
                  (find_stmt_start(tokens, i, &_ast_find_stmt_start_5),
                   _ast_find_stmt_start_5);

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
              sprintf_s(tmp_var, sizeof(tmp_var), "_tmp_cdd_%" SIZE_T_FMT "",
                        (size_t)(tmp_var_counter++));
#else
              sprintf(tmp_var, "_tmp_cdd_%" SIZE_T_FMT "",
                      (size_t)(tmp_var_counter++));
#endif

              /* Extract original args */
              call_args = (join_tokens_range(tokens, lparen + 1, rparen,
                                             &_ast_join_tokens_range_6),
                           _ast_join_tokens_range_6);

              /* Prepare injection */
#ifdef HAVE_ASPRINTF
              asprintf(&injection,
                       "%s %s; rc = %s(%s%s&%s); if (rc != 0) "
                       "return rc;\n  ",
                       rf->original_return_type, tmp_var, rf->name, call_args,
                       (strlen(call_args) > 0 ? ", " : ""), tmp_var);
#else
              injection = malloc(1024);
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
              sprintf_s(injection, 1024,
                        "%s %s; rc = %s(%s%s&%s); if (rc != 0) return "
                        "rc;\n  ",
                        rf->original_return_type, tmp_var, rf->name, call_args,
                        (strlen(call_args) > 0 ? ", " : ""), tmp_var);
#else
              sprintf(injection,
                      "%s %s; rc = %s(%s%s&%s); if (rc != 0) return "
                      "rc;\n  ",
                      rf->original_return_type, tmp_var, rf->name, call_args,
                      (strlen(call_args) > 0 ? ", " : ""), tmp_var);
#endif
#endif
              /* Inject before statement */
              patch_list_add(&patches, stmt_start, stmt_start, injection);

              /* Replace call with var */
              patch_list_add(
                  &patches, i, rparen + 1,
                  (c_cdd_strdup(tmp_var, &_ast_strdup_6), _ast_strdup_6));

              free(call_args);
              injected_rc = 1;
            }
          }
        }
      }
    }
  }

  /* 4. Transform Returns */
  if (transform) {
    for (i = 0; i < tokens->size; ++i) {
      if (tokens->tokens[i].kind == TOKEN_KEYWORD_RETURN) {

        if (transform->type == TRANSFORM_VOID_TO_INT) {
          size_t next = i + 1;
          while (next < tokens->size &&
                 tokens->tokens[next].kind == TOKEN_WHITESPACE)
            next++;
          if (next < tokens->size &&
              tokens->tokens[next].kind == TOKEN_SEMICOLON) {
            patch_list_add(
                &patches, i, next,
                (c_cdd_strdup("return 0", &_ast_strdup_7), _ast_strdup_7));
          }
        } else if (transform->type == TRANSFORM_RET_PTR_TO_ARG) {
          size_t semi = (find_semicolon(tokens, i, &_ast_find_semicolon_7),
                         _ast_find_semicolon_7);
          if (semi < tokens->size) {
            /* Fix: Check for inline unchecked alloc in return statement */
            int contains_alloc = 0;
            if (allocs) {
              size_t k;
              for (k = 0; k < allocs->size; k++) {
                /* If site is between return and semicolon */
                if (allocs->sites[k].token_index > i &&
                    allocs->sites[k].token_index < semi) {
                  contains_alloc = 1;
                  break;
                }
              }
            }

            if (contains_alloc) {
              /* Transform: return malloc(...) -> { Type _safe_ret =
               * malloc(...); if(!_safe_ret) return ENOMEM; *out = _safe_ret;
               * return 0; } */
              /* Extract expr between return (i) and semi (inclusive of nothing,
               * wait range excludes return kw) */
              char *expr = (join_tokens_range(tokens, i + 1, semi,
                                              &_ast_join_tokens_range_8),
                            _ast_join_tokens_range_8);
              char *replacement = NULL;

#ifdef HAVE_ASPRINTF
              asprintf(&replacement,
                       "{ %s _safe_ret = %s; if (!_safe_ret) return %s; *%s = "
                       "_safe_ret; return %s; }",
                       transform->return_type, expr, transform->error_code,
                       transform->arg_name, transform->success_code);
#else
              replacement = malloc(strlen(expr) + 256);
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
              sprintf_s(replacement, strlen(expr) + 256,
                        "{ %s _safe_ret = %s; if (!_safe_ret) return %s; *%s = "
                        "_safe_ret; return %s; }",
                        transform->return_type, expr, transform->error_code,
                        transform->arg_name, transform->success_code);
#else
              sprintf(replacement,
                      "{ %s _safe_ret = %s; if (!_safe_ret) return %s; *%s = "
                      "_safe_ret; return %s; }",
                      transform->return_type, expr, transform->error_code,
                      transform->arg_name, transform->success_code);
#endif
#endif
              /* Replace entire statement "return ...;" */
              patch_list_add(&patches, i, semi + 1, replacement);
              free(expr);
            } else {
              /* Replace return val; -> *out = val; return 0; */
              patch_list_add(
                  &patches, i, i + 1,
                  (c_cdd_strdup("*out =", &_ast_strdup_8), _ast_strdup_8));
              patch_list_add(
                  &patches, semi, semi + 1,
                  (c_cdd_strdup("; return 0;", &_ast_strdup_9), _ast_strdup_9));
            }
          }
        }
      }
    }

    if (transform->type == TRANSFORM_VOID_TO_INT && tokens->size > 0) {
      size_t last = tokens->size - 1;
      while (last > 0 && tokens->tokens[last].kind != TOKEN_RBRACE)
        last--;

      if (tokens->tokens[last].kind == TOKEN_RBRACE) {
        size_t prev_stmt = last;
        int has_ret = 0;
        while (prev_stmt > 0) {
          prev_stmt--;
          if (tokens->tokens[prev_stmt].kind == TOKEN_KEYWORD_RETURN) {
            has_ret = 1;
            break;
          }
          if (tokens->tokens[prev_stmt].kind == TOKEN_SEMICOLON ||
              tokens->tokens[prev_stmt].kind == TOKEN_RBRACE ||
              tokens->tokens[prev_stmt].kind == TOKEN_LBRACE)
            break;
        }
        if (!has_ret) {
          patch_list_add(
              &patches, last, last,
              (c_cdd_strdup(" return 0; ", &_ast_strdup_10), _ast_strdup_10));
        }
      }
    }
  }

  /* 5. Inject `int rc = 0;` if needed */
  if (injected_rc) {
    size_t k = 0;
    while (k < tokens->size && tokens->tokens[k].kind != TOKEN_LBRACE)
      k++;
    if (k < tokens->size) {
      patch_list_add(
          &patches, k + 1, k + 1,
          (c_cdd_strdup("\n  int rc = 0;", &_ast_strdup_11), _ast_strdup_11));
    }
  }

  /* 6. Execute Patching */
  rc = patch_list_apply(&patches, tokens, out_code);

  patch_list_free(&patches);
  return rc;
}
