#include <stdlib.h>

#include "simple.h"

/**
 * @brief Autogenerated docstring
 */
void Haz_cleanup(struct Haz *const haz) { free(haz); }

/**
 * @brief Autogenerated docstring
 */
void Foo_cleanup(struct Foo *const foo) {
  if (foo == NULL)
    return;
  Haz_cleanup(foo->haz);
  free(foo);
}
