/**
 * @file openapi2db.h
 * @brief Converts OpenAPI Specs into Database Schemas (DB IR).
 */

#ifndef C_CDD_OPENAPI2DB_H
#define C_CDD_OPENAPI2DB_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "classes/emit/database.h"
#include "openapi/parse/openapi.h"

/**
 * @brief Convert an OpenAPI Specification into a DatabaseSchema.
 *
 * @param spec The parsed OpenAPI specification.
 * @param schema Output DatabaseSchema.
 * @return 0 on success, non-zero otherwise.
 */
C_CDD_EXPORT /**
 * @brief Autogenerated docstring
 */
int openapi_to_db_schema(const struct OpenAPI_Spec *spec, struct DatabaseSchema *schema);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_OPENAPI2DB_H */
