void f() {
  char buf[100];
  char *str = "dummy";
  int dummy;
  void *ptr;
  strcpy(buf, str);
  strcat(buf, str);
  sprintf(buf, "%s", str);
  vsprintf(buf, "%s", ptr);
  wcscpy(ptr, ptr);
  wcscat(ptr, ptr);
  _mbscpy(ptr, ptr);
  _mbscat(ptr, ptr);
  swprintf(ptr, 100, L"%s", ptr);
  vswprintf(ptr, 100, L"%s", ptr);
  _strnset(buf, 'a', 10);
  _strset(buf, 'a');
  _mbsset(ptr, 'a');
  _strlwr(buf);
  _strupr(buf);
  _mbslwr(ptr);
  _mbsupr(ptr);
  _wcslwr(ptr);
  _wcsupr(ptr);
  gets(buf);
  tmpnam(buf);
  strlen(buf);
  strncpy(buf, str, 10);
  strncat(buf, str, 10);
  wcsncpy(ptr, ptr, 10);
  wcsncat(ptr, ptr, 10);
  _mbsncpy(ptr, ptr, 10);
  _mbsncat(ptr, ptr, 10);
  _mbsnset(ptr, 'a', 10);
  snprintf(buf, 100, "%s", str);
  vsnprintf(buf, 100, "%s", ptr);
  _snprintf(buf, 100, "%s", str);
  _vsnprintf(buf, 100, "%s", ptr);
  printf("%s", str);
  vprintf("%s", ptr);
  vfprintf(stdout, "%s", ptr);
  memcpy(buf, str, 10);
  memmove(buf, str, 10);
  wmemcpy(ptr, ptr, 10);
  wmemmove(ptr, ptr, 10);
  scanf("%s", buf);
  fscanf(stdin, "%s", buf);
  sscanf("123", "%s", buf);
  vscanf("%s", ptr);
  vfscanf(stdin, "%s", ptr);
  vsscanf("123", "%s", ptr);
  _itoa(123, buf, 10);
  _ltoa(123, buf, 10);
  _ultoa(123, buf, 10);
  _i64toa(123, buf, 10);
  _ui64toa(123, buf, 10);
  _itow(123, ptr, 10);
  _ltow(123, ptr, 10);
  _ultow(123, ptr, 10);
  _splitpath("path", buf, buf, buf, buf);
  _wsplitpath(ptr, ptr, ptr, ptr, ptr);
  _makepath(buf, buf, buf, buf, buf);
  _wmakepath(ptr, ptr, ptr, ptr, ptr);
  _gcvt(1.0, 10, buf);
  mbstowcs(ptr, str, 10);
  wcstombs(buf, ptr, 10);
  wctomb(buf, 'a');
  _searchenv("file", "env", buf);
  _wsearchenv(ptr, ptr, ptr);
  getenv("FOO");
  _wgetenv(ptr);
  _putenv("FOO=BAR");
  _wputenv(ptr);
  strerror(1);
  _strerror("err");
  _wcserror(1);
  _ecvt(1.0, 10, &dummy, &dummy);
  _fcvt(1.0, 10, &dummy, &dummy);
  strtok(buf, " ");
  wcstok(ptr, ptr);
  _mbstok(ptr, ptr);
  qsort(ptr, 10, 10, ptr);
  bsearch(ptr, ptr, 10, 10, ptr);
}
