/**
 * @file http_winhttp.c
 * @brief Implementation of the WinHTTP backend.
 *
 * WinHTTP specific implementation that ensures binary-safe responses
 * by accurately tracking bytes read from `WinHttpReadData` and explicitly
 * null-terminating the buffer for text safety without truncating binary
 * content.
 *
 * @author Samuel Marks
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>

#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
#include "c_cddConfig.h"
/* clang-format off */
#include "win_compat_sym.h"
#include <windows.h>
#include <winhttp.h>
/* clang-format on */
#else
/* Stub definitions */
/** @brief HINTERNET typedef */
typedef void *HINTERNET;
/** @brief BOOL definition */
typedef int BOOL;
/** @brief DWORD definition */
typedef unsigned long DWORD;
/** @brief LPVOID definition */
typedef void *LPVOID;
/** @brief FALSE definition */
#define FALSE 0
/** @brief TRUE definition */
#define TRUE 1
#endif

#include "functions/parse/fs.h"
#include "functions/parse/http_winhttp.h"
#include "functions/parse/str.h"

#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
#pragma comment(lib, "winhttp.lib")
#endif

struct HttpTransportContext {
  /** @brief hSession */
  /** @brief hSession */
  HINTERNET hSession;
  DWORD security_flags;
};

/* ... (Helpers like method_to_wide, safe_close_handle omitted for brevity if
   unchanged logic is same, but providing full file content below for
   correctness) ... */

#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
static /**
 * @brief Autogenerated docstring
 */
int method_to_wide(enum HttpMethod method, const wchar_t **out) {
  switch (method) {
  case HTTP_GET:
    *out = L"GET";
    return 0;
  case HTTP_POST:
    *out = L"POST";
    return 0;
  case HTTP_PUT:
    *out = L"PUT";
    return 0;
  case HTTP_DELETE:
    *out = L"DELETE";
    return 0;
  case HTTP_HEAD:
    *out = L"HEAD";
    return 0;
  case HTTP_OPTIONS:
    *out = L"OPTIONS";
    return 0;
  case HTTP_TRACE:
    *out = L"TRACE";
    return 0;
  case HTTP_QUERY:
    *out = L"QUERY";
    return 0;
  case HTTP_CONNECT:
    *out = L"CONNECT";
    return 0;
  case HTTP_PATCH:
    *out = L"PATCH";
    return 0;
  default:
    *out = L"GET";
    return 0;
  }
}

static /**
 * @brief Autogenerated docstring
 */
void safe_close_handle(HINTERNET *h) {
  if (h && *h) {
    WinHttpCloseHandle(*h);
    *h = NULL;
  }
}

static /**
 * @brief Autogenerated docstring
 */
int headers_to_wide_block(const struct HttpHeaders *headers,
                                 wchar_t **out) {
  size_t i;
  size_t total_wide_chars = 0;
  wchar_t *buf;
  wchar_t *p;

  *out = NULL;
  if (!headers || headers->count == 0)
    return 0;

  for (i = 0; i < headers->count; ++i) {
    total_wide_chars += strlen(headers->headers[i].key);
    total_wide_chars += strlen(headers->headers[i].value);
    total_wide_chars += 4;
  }
  total_wide_chars += 1;

  buf = (wchar_t *)calloc(total_wide_chars, sizeof(wchar_t));
  if (!buf)
    return ENOMEM;

  p = buf;
  for (i = 0; i < headers->count; ++i) {
    size_t written = 0;
    if (ascii_to_wide(headers->headers[i].key, p, total_wide_chars - (p - buf),
                      &written) != 0) {
      free(buf);
      return EIO;
    }
    p += written;
    wcscpy_s(p, total_wide_chars - (p - buf), L": ");
    p += 2;
    if (ascii_to_wide(headers->headers[i].value, p,
                      total_wide_chars - (p - buf), &written) != 0) {
      free(buf);
      return EIO;
    }
    p += written;
    wcscpy_s(p, total_wide_chars - (p - buf), L"\r\n");
    p += 2;
  }
  *out = buf;
  return 0;
}
#endif /* _WIN32 */

/**
 * @brief Autogenerated docstring
 */
int http_winhttp_global_init(void) { return 0; }
/**
 * @brief Autogenerated docstring
 */
void http_winhttp_global_cleanup(void) {}

/**
 * @brief Autogenerated docstring
 */
int http_winhttp_context_init(struct HttpTransportContext **ctx) {
#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
  HINTERNET hSession;
  if (!ctx)
    return EINVAL;

  hSession = WinHttpOpen(L"c_cdd/1.0", WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,
                         WINHTTP_NO_PROXY_NAME, WINHTTP_NO_PROXY_BYPASS, 0);
  if (!hSession)
    return EIO;

  *ctx = (struct HttpTransportContext *)malloc(
      sizeof(struct HttpTransportContext));
  if (!*ctx) {
    WinHttpCloseHandle(hSession);
    return ENOMEM;
  }
  (*ctx)->hSession = hSession;
  (*ctx)->security_flags = 0;
  return 0;
#else
  (void)ctx;
#ifdef ENOTSUP
  return ENOTSUP;
#else
  return EINVAL;
#endif
#endif
}

/**
 * @brief Autogenerated docstring
 */
void http_winhttp_context_free(struct HttpTransportContext *ctx) {
#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
  if (ctx) {
    if (ctx->hSession)
      WinHttpCloseHandle(ctx->hSession);
    free(ctx);
  }
#else
  (void)ctx;
#endif
}

/**
 * @brief Autogenerated docstring
 */
int http_winhttp_config_apply(struct HttpTransportContext *ctx,
                              const struct HttpConfig *config) {
#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
  DWORD dwTimeout;
  if (!ctx || !ctx->hSession || !config)
    return EINVAL;

  dwTimeout = (DWORD)config->timeout_ms;
  if (!WinHttpSetTimeouts(ctx->hSession, dwTimeout, dwTimeout, dwTimeout,
                          dwTimeout))
    return EIO;

  if (config->proxy_url) {
    WINHTTP_PROXY_INFO proxyInfo;
    wchar_t *wProxy = NULL;
    size_t wLen = 0;
    size_t bufSize = strlen(config->proxy_url) + 1;
    wProxy = (wchar_t *)calloc(bufSize, sizeof(wchar_t));
    if (!wProxy)
      return ENOMEM;
    if (ascii_to_wide(config->proxy_url, wProxy, bufSize, &wLen) != 0) {
      free(wProxy);
      return EINVAL;
    }
    proxyInfo.dwAccessType = WINHTTP_ACCESS_TYPE_NAMED_PROXY;
    proxyInfo.lpszProxy = wProxy;
    proxyInfo.lpszProxyBypass = NULL;
    if (!WinHttpSetOption(ctx->hSession, WINHTTP_OPTION_PROXY, &proxyInfo,
                          sizeof(proxyInfo))) {
      free(wProxy);
      return EIO;
    }
    free(wProxy);
  } else {
    WINHTTP_PROXY_INFO proxyInfo;
    proxyInfo.dwAccessType = WINHTTP_ACCESS_TYPE_DEFAULT_PROXY;
    proxyInfo.lpszProxy = NULL;
    proxyInfo.lpszProxyBypass = NULL;
    WinHttpSetOption(ctx->hSession, WINHTTP_OPTION_PROXY, &proxyInfo,
                     sizeof(proxyInfo));
  }

  ctx->security_flags = 0;
  if (!config->verify_peer) {
    ctx->security_flags |= SECURITY_FLAG_IGNORE_UNKNOWN_CA;
    ctx->security_flags |= SECURITY_FLAG_IGNORE_CERT_DATE_INVALID;
  }
  if (!config->verify_host) {
    ctx->security_flags |= SECURITY_FLAG_IGNORE_CERT_CN_INVALID;
  }
  return 0;
#else
  (void)ctx;
  (void)config;
#ifdef ENOTSUP
  return ENOTSUP;
#else
  return EINVAL;
#endif
#endif
}

/** @brief CLEANUP_AND_RET definition */
#define CLEANUP_AND_RET(err)                                                   \
  do {                                                                         \
    rc = (err);                                                                \
    goto cleanup;                                                              \
  } while (0)

/**
 * @brief Autogenerated docstring
 */
int http_winhttp_send(struct HttpTransportContext *ctx,
                      const struct HttpRequest *req,
                      struct HttpResponse **res) {
#if defined(_WIN32) && (!defined(_MSC_VER) || _MSC_VER >= 1600)
  HINTERNET hConnect = NULL, hRequest = NULL;
  URL_COMPONENTS urlComp;
  wchar_t *wUrl = NULL;
  wchar_t *wHeaders = NULL;
  wchar_t *hostName = NULL;
  wchar_t *urlPath = NULL;
  int rc = 0;
  const wchar_t *wmethod = NULL;
  size_t wLen = 0;
  DWORD dwStatusCode = 0;
  DWORD dwSize = sizeof(dwStatusCode);

  /* Body reading state */
  char *readBuf = NULL;
  char *totalBody = NULL;
  size_t totalSize = 0;
  DWORD dwDownloaded = 0;

  if (!ctx || !ctx->hSession || !req || !res)
    return EINVAL;

  {
    size_t cap = strlen(req->url) + 1;
    wUrl = (wchar_t *)malloc(cap * sizeof(wchar_t));
    if (!wUrl)
      return ENOMEM;
    if (ascii_to_wide(req->url, wUrl, cap, &wLen) != 0) {
      free(wUrl);
      return EINVAL;
    }
  }

  memset(&urlComp, 0, sizeof(urlComp));
  urlComp.dwStructSize = sizeof(urlComp);
  hostName = (wchar_t *)calloc(wLen + 1, sizeof(wchar_t));
  urlPath = (wchar_t *)calloc(wLen + 1, sizeof(wchar_t));
  if (!hostName || !urlPath) {
    free(wUrl);
    if (hostName)
      free(hostName);
    if (urlPath)
      free(urlPath);
    return ENOMEM;
  }
  urlComp.lpszHostName = hostName;
  urlComp.dwHostNameLength = (DWORD)wLen + 1;
  urlComp.lpszUrlPath = urlPath;
  urlComp.dwUrlPathLength = (DWORD)wLen + 1;

  if (!WinHttpCrackUrl(wUrl, (DWORD)wcslen(wUrl), 0, &urlComp)) {
    CLEANUP_AND_RET(EINVAL);
  }

  hConnect = WinHttpConnect(ctx->hSession, urlComp.lpszHostName,
                            (INTERNET_PORT)urlComp.nPort, 0);
  if (!hConnect)
    CLEANUP_AND_RET(EIO);

  
  method_to_wide(req->method, &wmethod);
  hRequest = WinHttpOpenRequest(
      hConnect, wmethod, urlComp.lpszUrlPath, NULL, WINHTTP_NO_REFERER,
      WINHTTP_DEFAULT_ACCEPT_TYPES,
      (urlComp.nScheme == INTERNET_SCHEME_HTTPS) ? WINHTTP_FLAG_SECURE : 0);
  if (!hRequest)
    CLEANUP_AND_RET(EIO);

  if (ctx->security_flags != 0) {
    WinHttpSetOption(hRequest, WINHTTP_OPTION_SECURITY_FLAGS,
                     &ctx->security_flags, sizeof(ctx->security_flags));
  }

  if (req->headers.count > 0) {
    if (headers_to_wide_block(&req->headers, &wHeaders) != 0)
      CLEANUP_AND_RET(ENOMEM);
    if (wHeaders) {
      WinHttpAddRequestHeaders(hRequest, wHeaders, (DWORD)-1L,
                               WINHTTP_ADDREQ_FLAG_ADD);
    }
  }

  if (!WinHttpSendRequest(hRequest, WINHTTP_NO_ADDITIONAL_HEADERS, 0,
                          req->body ? req->body : WINHTTP_NO_REQUEST_DATA,
                          (DWORD)req->body_len, (DWORD)req->body_len, 0)) {
    CLEANUP_AND_RET(EIO);
  }

  if (!WinHttpReceiveResponse(hRequest, NULL))
    CLEANUP_AND_RET(EIO);

  if (!WinHttpQueryHeaders(
          hRequest, WINHTTP_QUERY_STATUS_CODE | WINHTTP_QUERY_FLAG_NUMBER,
          WINHTTP_HEADER_NAME_BY_INDEX, &dwStatusCode, &dwSize,
          WINHTTP_NO_HEADER_INDEX)) {
    CLEANUP_AND_RET(EIO);
  }

  /* Read Body Cycle */
  readBuf = (char *)malloc(8192);
  if (!readBuf)
    CLEANUP_AND_RET(ENOMEM);

  do {
    dwSize = 0;
    if (!WinHttpQueryDataAvailable(hRequest, &dwSize))
      CLEANUP_AND_RET(EIO);
    if (dwSize == 0)
      break;
    if (dwSize > 8192)
      dwSize = 8192;

    if (!WinHttpReadData(hRequest, (LPVOID)readBuf, dwSize, &dwDownloaded))
      CLEANUP_AND_RET(EIO);

    if (dwDownloaded > 0) {
      char *new_ptr = (char *)realloc(totalBody, totalSize + dwDownloaded + 1);
      if (!new_ptr)
        CLEANUP_AND_RET(ENOMEM);
      totalBody = new_ptr;
      memcpy(totalBody + totalSize, readBuf, dwDownloaded);
      totalSize += dwDownloaded;
      totalBody[totalSize] = '\0'; /* Null terminate for text safety */
    }
  } while (dwSize > 0);

  *res = (struct HttpResponse *)calloc(1, sizeof(struct HttpResponse));
  if (!*res)
    CLEANUP_AND_RET(ENOMEM);
  if (http_response_init(*res) != 0) {
    free(*res);
    *res = NULL;
    CLEANUP_AND_RET(ENOMEM);
  }

  (*res)->status_code = (int)dwStatusCode;
  (*res)->body = totalBody;
  (*res)->body_len = totalSize;
  totalBody = NULL;

cleanup:
  safe_close_handle(&hRequest);
  safe_close_handle(&hConnect);
  if (wUrl)
    free(wUrl);
  if (wHeaders)
    free(wHeaders);
  if (hostName)
    free(hostName);
  if (urlPath)
    free(urlPath);
  if (readBuf)
    free(readBuf);
  if (totalBody)
    free(totalBody);

  return rc;
#else
  (void)ctx;
  (void)req;
  (void)res;
#ifdef ENOTSUP
  return ENOTSUP;
#else
  return EINVAL;
#endif
#endif
}
