/**
 * @file migration_runner.h
 * @brief Logic for applying and rolling back SQL migrations.
 *
 * @author Samuel Marks
 */

#ifndef C_CDD_MIGRATION_RUNNER_H
#define C_CDD_MIGRATION_RUNNER_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* clang-format off */
#include "c_cdd_export.h"
#include <stddef.h>
/* clang-format on */

/**
 * @brief Apply a migration file (run the UP statements).
 *
 * Connects to the database using the connection string from the `DATABASE_URL`
 * environment variable and executes the parsed UP statement.
 *
 * @param[in] filepath Path to the migration file.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    apply_migration(const char *filepath);

/**
 * @brief Rollback a migration file (run the DOWN statements).
 *
 * Connects to the database using the connection string from the `DATABASE_URL`
 * environment variable and executes the parsed DOWN statement.
 *
 * @param[in] filepath Path to the migration file.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    rollback_migration(const char *filepath);

/**
 * @brief Run all pending UP migrations in a directory.
 *
 * Connects to the database using `DATABASE_URL`, ensures the tracking table
 * exists, and applies any `.sql` migrations in `migrations_dir` that are not
 * yet recorded, in alphabetical order.
 *
 * @param[in] migrations_dir Path to the directory containing `.sql` files.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    run_pending_migrations(const char *migrations_dir);

/**
 * @brief Rollback the last applied DOWN migration.
 *
 * Connects to the database using `DATABASE_URL`, reads the last applied
 * migration from the tracking table, and executes its DOWN statement,
 * then removes the record.
 *
 * @param[in] migrations_dir Path to the directory containing `.sql` files.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    rollback_last_migration(const char *migrations_dir);

/**
 * @brief Create a new boilerplate migration file.
 *
 * @param[in] migrations_dir Directory to place the file.
 * @param[in] name The name suffix for the migration file.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    create_migration_file(const char *migrations_dir, const char *name);

/**
 * @brief Drop and recreate the database schema, then run all pending
 * migrations.
 *
 * @param[in] migrations_dir Directory containing `.sql` files.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    reset_database(const char *migrations_dir);

/**
 * @brief Setup a test database dynamically in CI mode.
 *
 * This will create a database if it doesn't exist, connect to it,
 * and execute all pending migrations. It requires `DATABASE_URL`
 * to have administrative privileges.
 *
 * @param[in] db_name The name of the test database to create.
 * @param[in] migrations_dir Directory containing `.sql` migrations.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    setup_test_database(const char *db_name, const char *migrations_dir);

/**
 * @brief Seed the database with SQL test data.
 *
 * @param[in] seed_filepath Path to the `.sql` seed file.
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    seed_database(const char *seed_filepath);

/**
 * @brief Dump the current database schema to a file.
 *
 * @param[in] out_filepath Path to the output file (e.g. `schema.sql`).
 * @return 0 on success, non-zero on failure.
 */
extern C_CDD_EXPORT /**
                     * @brief Autogenerated docstring
                     */
    int
    dump_schema(const char *out_filepath);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* C_CDD_MIGRATION_RUNNER_H */
