/**
 * @file strategy.c
 * @brief Implementation of safety injection strategies.
 *
 * @author Samuel Marks
 */

/* clang-format off */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "functions/parse/str.h" /* For string duplication utilities if specific needed */
#include "functions/parse/strategy.h"
/* clang-format on */

/* Common constants */
/* Note: In a larger system these might be configurable via context struct */
static const char *DEFAULT_ERROR_CODE = "ENOMEM";

/* Internal helpers */

/**
 * @brief Find explicit token indices for range extractions.
 */
static /**
        * @brief Autogenerated docstring
        */
    int
    find_next_token_idx(const struct TokenList *tokens, size_t start,
                        enum TokenKind kind, size_t *_out_val) {
  size_t i;
  for (i = start; i < tokens->size; ++i) {
    if (tokens->tokens[i].kind == kind) {
      *_out_val = i;
      return 0;
    }
  }
  {
    *_out_val = tokens->size;
    return 0;
  }
}

static /**
        * @brief Autogenerated docstring
        */
    int
    range_to_string(const struct TokenList *tokens, size_t start, size_t end,
                    char **_out_val) {
  size_t len = 0;
  size_t i;
  char *buf, *p;

  if (start >= end) {
    char *empty = (char *)malloc(1);
    if (empty)
      *empty = '\0';
    {
      *_out_val = empty;
      return 0;
    }
  }

  for (i = start; i < end; ++i)
    len += tokens->tokens[i].length;

  buf = (char *)malloc(len + 1);
  if (!buf) {
    *_out_val = NULL;
    return 0;
  }

  p = buf;
  for (i = start; i < end; ++i) {
    memcpy(p, tokens->tokens[i].start, tokens->tokens[i].length);
    p += tokens->tokens[i].length;
  }
  *p = '\0';
  {
    *_out_val = buf;
    return 0;
  }
}

/* --- Realloc Strategy --- */

/**
 * @brief Autogenerated docstring
 */
int strategy_rewrite_realloc(const struct TokenList *tokens,
                             const struct AllocationSite *site,
                             const size_t semi_idx, struct PatchList *patches) {
  size_t _ast_find_next_token_idx_0;
  bool _ast_token_matches_string_1;
  char *_ast_range_to_string_2;
  size_t call_idx = site->token_index;
  size_t lparen_idx;
  size_t assign_op_idx = 0;
  size_t stmt_start = 0;
  int is_self_assign = 0;

  if (!site->var_name)
    return 0;

  /* 1. Locate assignment `=` backwards from call */
  {
    size_t i = call_idx;
    while (i > 0) {
      i--;
      if (tokens->tokens[i].kind == TOKEN_ASSIGN) {
        assign_op_idx = i;
        break;
      }
      /* Boundary check to stop search */
      if (tokens->tokens[i].kind == TOKEN_SEMICOLON ||
          tokens->tokens[i].kind == TOKEN_LBRACE ||
          tokens->tokens[i].kind == TOKEN_RBRACE) {
        break;
      }
    }
  }

  if (assign_op_idx == 0)
    return 0; /* Not an assignment */

  /* 2. Find start of statement */
  stmt_start = assign_op_idx;
  while (stmt_start > 0) {
    size_t prev = stmt_start - 1;
    if (tokens->tokens[prev].kind == TOKEN_SEMICOLON ||
        tokens->tokens[prev].kind == TOKEN_LBRACE ||
        tokens->tokens[prev].kind == TOKEN_RBRACE) {
      break;
    }
    stmt_start--;
  }
  /* Skip leading whitespace */
  while (stmt_start < assign_op_idx &&
         tokens->tokens[stmt_start].kind == TOKEN_WHITESPACE)
    stmt_start++;

  /* 3. Check arguments: realloc(ptr, size) */
  lparen_idx = (find_next_token_idx(tokens, call_idx, TOKEN_LPAREN,
                                    &_ast_find_next_token_idx_0),
                _ast_find_next_token_idx_0);
  if (lparen_idx >= tokens->size)
    return 0;

  {
    /* Extract first arg name crudely */
    size_t start_arg = lparen_idx + 1;
    while (start_arg < tokens->size &&
           tokens->tokens[start_arg].kind == TOKEN_WHITESPACE)
      start_arg++;

    if (start_arg < tokens->size &&
        tokens->tokens[start_arg].kind == TOKEN_IDENTIFIER) {
      /* Compare against var_name */
      if ((token_matches_string(&tokens->tokens[start_arg], site->var_name,
                                &_ast_token_matches_string_1),
           _ast_token_matches_string_1)) {
        is_self_assign = 1;
      }
    }
  }

  if (is_self_assign) {
    char *call_expr = NULL;
    char *replacement = NULL;

    /* Extract "realloc(p, n)" text */
    call_expr =
        (range_to_string(tokens, call_idx, semi_idx, &_ast_range_to_string_2),
         _ast_range_to_string_2);
    if (!call_expr)
      return ENOMEM;

    /* Build safe block */
    /* { void *_safe_tmp = call_expr; if (!_safe_tmp) return ENOMEM; var =
     * _safe_tmp; } */
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER) ||                         \
    defined(__STDC_LIB_EXT1__) && __STDC_WANT_LIB_EXT1__
    /* Use explicit size calc + sprintf_s or malloc+sprintf in C89 portable
       way? The codebase uses asprintf extension usually. Assuming
       asprintf/compatibility macro exists from str_utils context. */
    /* Wait, asprintf is provided by project macros. */
#endif
    /* Using asprintf for consistency as per previous project standards */
    /* However, strict C89 doesn't have it. We assume project provides it via
     * c89stringutils. */
#ifdef HAVE_ASPRINTF
    if (asprintf(&replacement,
                 "{ void *_safe_tmp = %s; if (!_safe_tmp) return %s; %s = "
                 "_safe_tmp; }",
                 call_expr, DEFAULT_ERROR_CODE, site->var_name) == -1) {
      free(call_expr);
      return ENOMEM;
    }
#else
    /* Fallback logic or assume HAVE_ASPRINTF is defined by build system */
    /* This sample assumes HAVE_ASPRINTF */
    {
      size_t replacement_len = strlen(call_expr) + strlen(site->var_name) + 128;
      replacement = (char *)malloc(replacement_len);
      if (replacement) {
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
        sprintf_s(replacement, replacement_len,
                  "{ void *_safe_tmp = %s; if (!_safe_tmp) return %s; %s = "
                  "_safe_tmp; }",
                  call_expr, DEFAULT_ERROR_CODE, site->var_name);
#else
        sprintf(replacement,
                "{ void *_safe_tmp = %s; if (!_safe_tmp) return %s; %s = "
                "_safe_tmp; }",
                call_expr, DEFAULT_ERROR_CODE, site->var_name);
#endif
      } else {
        free(call_expr);
        return ENOMEM;
      }
    }
#endif
    free(call_expr);

    /* Replace the entire statement "p = realloc(...);" with the block */
    /* Range: [stmt_start, semi_idx + 1) (to include semicolon) */
    return patch_list_add(patches, stmt_start, semi_idx + 1, replacement);
  }

  return 0;
}

/* --- General Safety Injection --- */

/**
 * @brief Autogenerated docstring
 */
int strategy_inject_safety_checks(const struct TokenList *tokens,
                                  const struct AllocationSiteList *allocs,
                                  struct PatchList *patches) {
  size_t _ast_find_next_token_idx_3;
  size_t i;
  if (!tokens || !allocs || !patches)
    return EINVAL;

  for (i = 0; i < allocs->size; ++i) {
    size_t semi_idx;
    char *injection = NULL;
    const struct AllocationSite *site = &allocs->sites[i];

    if (site->is_checked)
      continue;

    semi_idx = (find_next_token_idx(tokens, site->token_index, TOKEN_SEMICOLON,
                                    &_ast_find_next_token_idx_3),
                _ast_find_next_token_idx_3);
    if (semi_idx >= tokens->size)
      continue;

    /* Dispatch realloc strategy */
    if (strcmp(site->spec->name, "realloc") == 0) {
      size_t old_size = patches->size;
      int rc = strategy_rewrite_realloc(tokens, site, semi_idx, patches);
      if (rc != 0)
        return rc;
      /* If matched and patched, skip standard injection logic */
      if (patches->size > old_size)
        continue;
    }

    if (!site->var_name)
      continue;

    /* Build check string */
    /* We inject AFTER the semicolon */
    if (site->spec->check_style == CHECK_PTR_NULL) {
      /* " if (!var) { return ENOMEM; }" */
      size_t len = strlen(site->var_name) + 40;
      injection = (char *)malloc(len);
      if (!injection)
        return ENOMEM;
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
      sprintf_s(injection, len, " if (!%s) { return %s; }", site->var_name,
                DEFAULT_ERROR_CODE);
#else
      sprintf(injection, " if (!%s) { return %s; }", site->var_name,
              DEFAULT_ERROR_CODE);
#endif

    } else if (site->spec->check_style == CHECK_INT_NEGATIVE) {
      size_t len = strlen(site->var_name) + 40;
      injection = (char *)malloc(len);
      if (!injection)
        return ENOMEM;
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
      sprintf_s(injection, len, " if (%s < 0) { return %s; }", site->var_name,
                DEFAULT_ERROR_CODE);
#else
      sprintf(injection, " if (%s < 0) { return %s; }", site->var_name,
              DEFAULT_ERROR_CODE);
#endif

    } else if (site->spec->check_style == CHECK_INT_NONZERO) {
      size_t len = strlen(site->var_name) + 40;
      injection = (char *)malloc(len);
      if (!injection)
        return ENOMEM;
#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
      sprintf_s(injection, len, " if (%s != 0) { return %s; }", site->var_name,
                DEFAULT_ERROR_CODE);
#else
      sprintf(injection, " if (%s != 0) { return %s; }", site->var_name,
              DEFAULT_ERROR_CODE);
#endif
    } else {
      /* Unknown -> skip */
      continue;
    }

    /* Add patch: Insert at semi_idx + 1 (Start==End for insertion) */
    if (patch_list_add(patches, semi_idx + 1, semi_idx + 1, injection) != 0) {
      /* patch_list_add frees injection on failure, but we rely on its behavior.
         Check implementation: Yes, it handles free on failure. */
      return ENOMEM;
    }
  }

  return 0;
}
