/**
 * @file test_db_codegen.h
 * @brief Unit tests for generating C ORM and DB SQL.
 */

#ifndef TEST_DB_CODEGEN_H
#define TEST_DB_CODEGEN_H

#include <greatest.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "classes/emit/database.h"
#include "classes/emit/db_codegen.h"

/**
 * @brief Autogenerated docstring
 */
int test_db_codegen_sql_sqlite(TEST *_out_val) {
  struct DatabaseSchema schema;
  struct DatabaseTable table;
  struct DatabaseColumn cols[3];
  char buffer[1024] = {0};
  FILE *f;
  int rc;

  db_schema_init(&schema);
  schema.name = "TestDB";
  schema.tables = &table;
  schema.n_tables = 1;

  table.name = "users";
  table.columns = cols;
  table.n_columns = 3;

  memset(cols, 0, sizeof(cols));

  cols[0].name = "id";
  cols[0].type = DB_COL_TYPE_INTEGER;
  cols[0].is_primary_key = 1;

  cols[1].name = "username";
  cols[1].type = DB_COL_TYPE_VARCHAR;
  cols[1].is_unique = 1;
  cols[1].is_nullable = 1;

  cols[2].name = "age";
  cols[2].type = DB_COL_TYPE_INTEGER;
  cols[2].is_nullable = 0;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  rc = fopen_s(&f, "test_db_codegen_sqlite.sql", "w+");
  if (rc != 0) FAILm("Could not open file");
#else
  f = fopen("test_db_codegen_sqlite.sql", "w+");
  if (!f) FAILm("Could not open file");
#endif

  rc = db_codegen_sql(&schema, f, "sqlite");
  ASSERT_EQ(0, rc);

  fseek(f, 0, SEEK_SET);
  fread(buffer, 1, sizeof(buffer) - 1, f);
  fclose(f);
  remove("test_db_codegen_sqlite.sql");

  ASSERT(strstr(buffer, "CREATE TABLE IF NOT EXISTS users (") != NULL);
  ASSERT(strstr(buffer, "id INTEGER PRIMARY KEY") != NULL);
  ASSERT(strstr(buffer, "username TEXT UNIQUE") != NULL);
  ASSERT(strstr(buffer, "age INTEGER NOT NULL") != NULL);

  PASS();
}

/**
 * @brief Autogenerated docstring
 */
int test_db_codegen_sql_postgres(TEST *_out_val) {
  struct DatabaseSchema schema;
  struct DatabaseTable table;
  struct DatabaseColumn cols[2];
  char buffer[1024] = {0};
  FILE *f;
  int rc;

  db_schema_init(&schema);
  schema.name = "TestDB";
  schema.tables = &table;
  schema.n_tables = 1;

  table.name = "posts";
  table.columns = cols;
  table.n_columns = 2;

  memset(cols, 0, sizeof(cols));

  cols[0].name = "id";
  cols[0].type = DB_COL_TYPE_INTEGER;
  cols[0].is_primary_key = 1;

  cols[1].name = "title";
  cols[1].type = DB_COL_TYPE_VARCHAR;
  cols[1].is_nullable = 1;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  rc = fopen_s(&f, "test_db_codegen_pg.sql", "w+");
  if (rc != 0) FAILm("Could not open file");
#else
  f = fopen("test_db_codegen_pg.sql", "w+");
  if (!f) FAILm("Could not open file");
#endif

  rc = db_codegen_sql(&schema, f, "postgres");
  ASSERT_EQ(0, rc);

  fseek(f, 0, SEEK_SET);
  fread(buffer, 1, sizeof(buffer) - 1, f);
  fclose(f);
  remove("test_db_codegen_pg.sql");

  ASSERT(strstr(buffer, "CREATE TABLE IF NOT EXISTS posts (") != NULL);
  ASSERT(strstr(buffer, "id INTEGER PRIMARY KEY") != NULL);
  ASSERT(strstr(buffer, "title VARCHAR") != NULL);

  PASS();
}

/**
 * @brief Autogenerated docstring
 */
int test_db_codegen_c_header(TEST *_out_val) {
  struct DatabaseSchema schema;
  struct DatabaseTable table;
  struct DatabaseColumn cols[2];
  char buffer[1024] = {0};
  FILE *f;
  int rc;

  db_schema_init(&schema);
  schema.name = "TestDB";
  schema.tables = &table;
  schema.n_tables = 1;

  table.name = "Role";
  table.columns = cols;
  table.n_columns = 2;

  memset(cols, 0, sizeof(cols));

  cols[0].name = "id";
  cols[0].type = DB_COL_TYPE_INTEGER;

  cols[1].name = "name";
  cols[1].type = DB_COL_TYPE_VARCHAR;

#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
  rc = fopen_s(&f, "test_db_codegen_hdr.h", "w+");
  if (rc != 0) FAILm("Could not open file");
#else
  f = fopen("test_db_codegen_hdr.h", "w+");
  if (!f) FAILm("Could not open file");
#endif

  rc = db_codegen_struct_header(&schema, f, "TEST_DB_CODEGEN_HDR_H");
  ASSERT_EQ(0, rc);

  fseek(f, 0, SEEK_SET);
  fread(buffer, 1, sizeof(buffer) - 1, f);
  fclose(f);
  remove("test_db_codegen_hdr.h");

  ASSERT(strstr(buffer, "#ifndef TEST_DB_CODEGEN_HDR_H") != NULL);
  ASSERT(strstr(buffer, "struct Role {") != NULL);
  ASSERT(strstr(buffer, "int id;") != NULL);
  ASSERT(strstr(buffer, "char * name;") != NULL);

  PASS();
}

int db_codegen_suite) {
  RUN_TEST(test_db_codegen_sql_sqlite);
  RUN_TEST(test_db_codegen_sql_postgres);
  RUN_TEST(test_db_codegen_c_header);
}

#endif /* TEST_DB_CODEGEN_H */
