/* Auto-generated by cdd-c */
pub mod sys;

pub use sys::*;

use std::ffi::CStr;
use std::ffi::CString;
use std::os::raw::c_char;

#[derive(Debug)]
pub struct FfiError {
    pub code: i32,
    pub message: String,
}

impl std::fmt::Display for FfiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "FfiError({}): {}", self.code, self.message)
    }
}

impl std::error::Error for FfiError {}

pub struct Wrapper;

impl Wrapper {
}
