/* Auto-generated by cdd-c */
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Point {
    pub x: i32,
}

extern "C" {
}
